const { createClient } = require('@supabase/supabase-js');
require('dotenv').config({ path: '.env.local' });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY // Use service role for admin insert
);

async function seedInstitutions() {
  const institutions = [
    { name: 'Academic City University', abbreviation: 'ACity', domain: 'acity.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Accra Metropolitan University', abbreviation: 'AMU', domain: 'accrametrouni.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'African University of Communication and Business', abbreviation: 'AUCB', domain: 'aucb.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Akrofi-Christaller Institute of Theology, Mission and Culture', abbreviation: 'ACI', domain: 'aci.edu.gh', country: 'Ghana', city: 'Akropong', type: 'Private University', verified: true },
    { name: 'All Nations University', abbreviation: 'ANU', domain: 'anu.edu.gh', country: 'Ghana', city: 'Koforidua', type: 'Private University', verified: true },
    { name: 'Ashesi University', abbreviation: 'Ashesi', domain: 'ashesi.edu.gh', country: 'Ghana', city: 'Berekuso', type: 'Private University', verified: true },
    { name: 'Catholic University College of Ghana', abbreviation: 'CUG', domain: 'cug.edu.gh', country: 'Ghana', city: 'Sunyani', type: 'Private University', verified: true },
    { name: 'Central University', abbreviation: 'CU', domain: 'central.edu.gh', country: 'Ghana', city: 'Accra / Tema', type: 'Private University', verified: true },
    { name: 'Christian Service University', abbreviation: 'CSUC', domain: 'csuc.edu.gh', country: 'Ghana', city: 'Kumasi', type: 'Private University', verified: true },
    { name: 'Ensign Global University', abbreviation: 'EGU', domain: 'ensign.edu.gh', country: 'Ghana', city: 'Kpong', type: 'Private University', verified: true },
    { name: 'Entrance University of Health Sciences', abbreviation: 'EUHS', domain: 'entrance.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Family Health University', abbreviation: 'FHU', domain: 'familyhealthuniversity.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Garden City University', abbreviation: 'GCU', domain: 'gcuc.edu.gh', country: 'Ghana', city: 'Kumasi', type: 'Private University', verified: true },
    { name: 'Heritage Christian University', abbreviation: 'HCU', domain: 'hcu.edu.gh', country: 'Ghana', city: 'Amasaman', type: 'Private University', verified: true },
    { name: 'KAAF University', abbreviation: 'KAAF', domain: 'kaaf.edu.gh', country: 'Ghana', city: 'Gomoa Fetteh', type: 'Private University', verified: true },
    { name: 'Knutsford University', abbreviation: 'Knutsford', domain: 'knutsford.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Methodist University Ghana', abbreviation: 'MUCG', domain: 'methodist.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'NiBS University', abbreviation: 'NiBS', domain: 'nibs.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Pentecost University', abbreviation: 'PU', domain: 'pentvars.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Presbyterian University', abbreviation: 'PUC', domain: 'presbyuniversity.edu.gh', country: 'Ghana', city: 'Abetifi', type: 'Private University', verified: true },
    { name: 'Thrivus University for Biomedical Science and Technology', abbreviation: 'Thrivus', domain: 'thrivus.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Trinity Theological Seminary', abbreviation: 'TTS', domain: 'tts.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'University of Gold Coast', abbreviation: 'UGC', domain: 'ugc.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Valley View University', abbreviation: 'VVU', domain: 'vvu.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Business University of Costa Rica', abbreviation: 'UNEM', domain: 'unem.edu', country: 'Ghana', city: 'Kumasi', type: 'Foreign Affiliated', verified: true },
    { name: 'Lancaster University Ghana', abbreviation: 'LUG', domain: 'lancaster.edu.gh', country: 'Ghana', city: 'Accra', type: 'Foreign Affiliated', verified: true },
    { name: 'Malaysia University of Science and Technology Ghana Campus', abbreviation: 'MUST', domain: 'must.edu.my', country: 'Ghana', city: 'Accra', type: 'Foreign Affiliated', verified: true },
    { name: 'Open University of Malaysia Ghana Campus', abbreviation: 'OUM', domain: 'oum.edu.my', country: 'Ghana', city: 'Accra', type: 'Foreign Affiliated', verified: true },
    { name: 'Webster University Ghana', abbreviation: 'Webster', domain: 'webster.edu.gh', country: 'Ghana', city: 'Accra', type: 'Foreign Affiliated', verified: true },
    { name: 'Accra Institute of Technology', abbreviation: 'AIT', domain: 'ait.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Advance Global University College', abbreviation: 'AGUC', domain: 'advanceglobal.edu.gh', country: 'Ghana', city: 'Tamale', type: 'Private University', verified: true },
    { name: 'African Institute for Mathematical Sciences Ghana', abbreviation: 'AIMS Ghana', domain: 'aims.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'African University College of Communications', abbreviation: 'AUCC', domain: 'aucc.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Akim State College', abbreviation: 'ASC', domain: 'akimstate.edu.gh', country: 'Ghana', city: 'Akim Oda', type: 'Private University', verified: true },
    { name: 'Amen College of Health Sciences', abbreviation: 'ACHS', domain: 'amencollege.edu.gh', country: 'Ghana', city: 'Kumasi', type: 'Private University', verified: true },
    { name: 'Anglican University College of Technology', abbreviation: 'AUCT', domain: 'anglicanuc.edu.gh', country: 'Ghana', city: 'Nkoranza', type: 'Private University', verified: true },
    { name: 'Apex University College', abbreviation: 'Apex', domain: 'apexuniversity.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Apostolic Church Theological Seminary', abbreviation: 'ACTS', domain: 'acts.edu.gh', country: 'Ghana', city: 'Kumasi', type: 'Private University', verified: true },
    { name: 'Baldwin College', abbreviation: 'Baldwin', domain: 'baldwincollege.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'BlueCrest College', abbreviation: 'BlueCrest', domain: 'bluecrest.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Bunso Cocoa College', abbreviation: 'BCC', domain: 'bunsococoa.edu.gh', country: 'Ghana', city: 'Bunso', type: 'Private University', verified: true },
    { name: 'CSIR College of Science and Technology', abbreviation: 'CSIR-CST', domain: 'csircst.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Carest College of Health', abbreviation: 'Carest', domain: 'carest.edu.gh', country: 'Ghana', city: 'Hohoe', type: 'Private University', verified: true },
    { name: 'Central College of Science and Technology', abbreviation: 'CCST', domain: 'centralcollege.edu.gh', country: 'Ghana', city: 'Agona Swedru', type: 'Private University', verified: true },
    { name: 'China Europe International Business School Africa Campus', abbreviation: 'CEIBS', domain: 'ceibs.edu/gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Christ Apostolic University College', abbreviation: 'CAUC', domain: 'cauc.edu.gh', country: 'Ghana', city: 'Kumasi', type: 'Private University', verified: true },
    { name: 'College of Islamic Studies', abbreviation: 'CIS', domain: 'cis.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'College of Medicine and Allied Sciences', abbreviation: 'COMAS', domain: 'comas.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'DHI College of Health and Education', abbreviation: 'DHI', domain: 'dhicollege.edu.gh', country: 'Ghana', city: 'Kumasi', type: 'Private University', verified: true },
    { name: 'Data Link Institute of Business and Technology', abbreviation: 'DLIBT', domain: 'datalink.edu.gh', country: 'Ghana', city: 'Tema', type: 'Private University', verified: true },
    { name: 'Delexes University College', abbreviation: 'Delexes', domain: 'delexes.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Duffuor University College', abbreviation: 'DUC', domain: 'duffuoruniversity.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Entrepreneurship Training Institute', abbreviation: 'ETI', domain: 'eti.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Evangelical Presbyterian University College', abbreviation: 'EPUC', domain: 'epuc.edu.gh', country: 'Ghana', city: 'Ho', type: 'Private University', verified: true },
    { name: 'Fanaka International University College', abbreviation: 'Fanaka', domain: 'fanakauc.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Flosam Institute of Nursing and Allied Health Sciences', abbreviation: 'Flosam', domain: 'flosam.edu.gh', country: 'Ghana', city: 'Suhum', type: 'Private University', verified: true },
    { name: 'Fountainhead Christian University College', abbreviation: 'FCUC', domain: 'fountainhead.edu.gh', country: 'Ghana', city: 'Tema', type: 'Private University', verified: true },
    { name: 'GNAT Institute for Research and Industrial Relations Studies', abbreviation: 'GNAT-IRIRS', domain: 'gnatirrs.edu.gh', country: 'Ghana', city: 'Ejisu', type: 'Private University', verified: true },
    { name: 'Ghana Baptist University College', abbreviation: 'GBUC', domain: 'gbuc.edu.gh', country: 'Ghana', city: 'Kumasi', type: 'Private University', verified: true },
    { name: 'Ghana Christian University College', abbreviation: 'GCUC', domain: 'ghanacu.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Ghana Insurance College', abbreviation: 'GIC', domain: 'gic.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Global Theological Seminary', abbreviation: 'GTS', domain: 'globaltheological.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Good News Theological Seminary', abbreviation: 'GNTS', domain: 'goodnews.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'High Skies College', abbreviation: 'HSC', domain: 'highskies.edu.gh', country: 'Ghana', city: 'Tema', type: 'Private University', verified: true },
    { name: 'Holy Eucharist University College', abbreviation: 'HEUC', domain: 'holyeucharist.edu.gh', country: 'Ghana', city: 'Half Assini', type: 'Private University', verified: true },
    { name: 'Institute for Security, Disaster and Emergency Studies', abbreviation: 'ISDES', domain: 'isdes.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Institute of Development and Technology Management', abbreviation: 'IDTM', domain: 'idtm.edu.gh', country: 'Ghana', city: 'Cape Coast', type: 'Private University', verified: true },
    { name: 'Islamic University College', abbreviation: 'IUCG', domain: 'iucg.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'JACCD Design Institute Africa', abbreviation: 'JACCD', domain: 'jaccd.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Jackson University College', abbreviation: 'Jackson', domain: 'jacksonuniversity.edu.gh', country: 'Ghana', city: 'Kumasi', type: 'Private University', verified: true },
    { name: 'Jayee University College', abbreviation: 'Jayee', domain: 'jayeeuniversity.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Justking College', abbreviation: 'Justking', domain: 'justking.edu.gh', country: 'Ghana', city: 'Sefwi', type: 'Private University', verified: true },
    { name: 'Kessben University College', abbreviation: 'Kessben', domain: 'kessbenuniversity.edu.gh', country: 'Ghana', city: 'Kumasi', type: 'Private University', verified: true },
    { name: 'Kings University College', abbreviation: 'KUC', domain: 'kingsuniversity.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Klintaps College of Health and Allied Sciences', abbreviation: 'Klintaps', domain: 'klintaps.edu.gh', country: 'Ghana', city: 'Tema', type: 'Private University', verified: true },
    { name: 'Maranatha University College', abbreviation: 'Maranatha', domain: 'maranatha.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Medicare College of Applied Sciences', abbreviation: 'MCAS', domain: 'medicarecollege.edu.gh', country: 'Ghana', city: 'Kumasi', type: 'Private University', verified: true },
    { name: 'Miezah University College', abbreviation: 'Miezah', domain: 'miezahuniversity.edu.gh', country: 'Ghana', city: 'Kumasi', type: 'Private University', verified: true },
    { name: 'Millar Institute of Transdisciplinary And Development Studies', abbreviation: 'Millar', domain: 'millar.edu.gh', country: 'Ghana', city: 'Bolgatanga', type: 'Private University', verified: true },
    { name: 'Mountcrest University College', abbreviation: 'Mountcrest', domain: 'mountcrest.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'National Defence University', abbreviation: 'NDU', domain: 'ndu.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Nduom School of Business and Technology', abbreviation: 'NSBT', domain: 'nsbt.edu.gh', country: 'Ghana', city: 'Elmina', type: 'Private University', verified: true },
    { name: 'Neumann College', abbreviation: 'Neumann', domain: 'neumanncollege.edu.gh', country: 'Ghana', city: 'Kumasi', type: 'Private University', verified: true },
    { name: 'New Life College', abbreviation: 'NLC', domain: 'newlifecollege.edu.gh', country: 'Ghana', city: 'Tamale', type: 'Private University', verified: true },
    { name: 'Nyansapo College', abbreviation: 'Nyansapo', domain: 'nyansapo.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'OTE School of Journalism and Communication Studies', abbreviation: 'OTE', domain: 'oteschool.edu.gh', country: 'Ghana', city: 'Kumasi', type: 'Private University', verified: true },
    { name: 'Oheneba-Dornyo University College of Counselling Psychology', abbreviation: 'ODUCCP', domain: 'oduccp.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Organization Development Institute', abbreviation: 'ODI', domain: 'odi.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Palm University College', abbreviation: 'Palm', domain: 'palmuniversity.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Perez University College', abbreviation: 'Perez', domain: 'perezuniversity.edu.gh', country: 'Ghana', city: 'Winneba', type: 'Private University', verified: true },
    { name: 'Pharmatrust Professional College', abbreviation: 'Pharmatrust', domain: 'pharmatrust.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Radford University College', abbreviation: 'Radford', domain: 'radford.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Redeemer College of Health', abbreviation: 'RCH', domain: 'redeemercollege.edu.gh', country: 'Ghana', city: 'Tarkwa', type: 'Private University', verified: true },
    { name: 'Regent University College of Science and Technology', abbreviation: 'Regent', domain: 'regent.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Regentropfen University College', abbreviation: 'Regentropfen', domain: 'regentropfen.edu.gh', country: 'Ghana', city: 'Bongo', type: 'Private University', verified: true },
    { name: 'Rosebank International University College', abbreviation: 'Rosebank', domain: 'rosebank.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'SALT University College', abbreviation: 'SALT', domain: 'saltuniversity.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'SIIMT University College', abbreviation: 'SIIMT', domain: 'siimt.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Southshore University College', abbreviation: 'Southshore', domain: 'southshore.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Spiritan University College', abbreviation: 'SUC', domain: 'spiritan.edu.gh', country: 'Ghana', city: 'Ejisu', type: 'Private University', verified: true },
    { name: 'St. Mary\'s College of Health Science', abbreviation: 'SMCHS', domain: 'stmaryshealth.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Techbridge University College', abbreviation: 'Techbridge', domain: 'techbridge.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'University College of Agriculture and Environmental Studies', abbreviation: 'UCAES', domain: 'ucaes.edu.gh', country: 'Ghana', city: 'Bunso', type: 'Private University', verified: true },
    { name: 'University College of Management Studies', abbreviation: 'UCOMS', domain: 'ucoms.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'West End University College', abbreviation: 'West End', domain: 'westenduniversity.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Wisconsin International University College', abbreviation: 'WIUC', domain: 'wiuc-ghana.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Zenith University College', abbreviation: 'ZUC', domain: 'zenithuniversity.edu.gh', country: 'Ghana', city: 'Accra', type: 'Private University', verified: true },
    { name: 'Ghana Armed Forces Command and Staff College', abbreviation: 'GAFCSC', domain: 'gafcsc.mil.gh', country: 'Ghana', city: 'Accra', type: 'Public Professional', verified: true },
    { name: 'Ghana Institute of Journalism', abbreviation: 'GIJ', domain: 'gij.edu.gh', country: 'Ghana', city: 'Accra', type: 'Public Professional', verified: true },
    { name: 'Ghana Institute of Languages', abbreviation: 'GIL', domain: 'gil.edu.gh', country: 'Ghana', city: 'Accra', type: 'Public Professional', verified: true },
    { name: 'Ghana Institute of Surveying and Mapping', abbreviation: 'GISM', domain: 'gism.edu.gh', country: 'Ghana', city: 'Accra', type: 'Public Professional', verified: true },
    { name: 'Institute of Local Government Studies', abbreviation: 'ILGS', domain: 'ilgs.edu.gh', country: 'Ghana', city: 'Accra', type: 'Public Professional', verified: true },
    { name: 'Kofi Annan International Peacekeeping Training Centre', abbreviation: 'KAIPTC', domain: 'kaiptc.org', country: 'Ghana', city: 'Accra', type: 'Public Professional', verified: true },
    { name: 'National Film and Television Institute', abbreviation: 'NAFTI', domain: 'nafti.edu.gh', country: 'Ghana', city: 'Accra', type: 'Public Professional', verified: true },
    { name: 'Regional Maritime University', abbreviation: 'RMU', domain: 'rmu.edu.gh', country: 'Ghana', city: 'Accra', type: 'Public Professional', verified: true },
    { name: 'Accra Technical University', abbreviation: 'ATU', domain: 'atu.edu.gh', country: 'Ghana', city: 'Accra', type: 'Technical University', verified: true },
    { name: 'Bolgatanga Technical University', abbreviation: 'BTU', domain: 'btu.edu.gh', country: 'Ghana', city: 'Bolgatanga', type: 'Technical University', verified: true },
    { name: 'Cape Coast Technical University', abbreviation: 'CCTU', domain: 'cctu.edu.gh', country: 'Ghana', city: 'Cape Coast', type: 'Technical University', verified: true },
    { name: 'Dr. Hilla Limann Technical University', abbreviation: 'DHL-TU', domain: 'dhl-tu.edu.gh', country: 'Ghana', city: 'Wa', type: 'Technical University', verified: true },
    { name: 'Ho Technical University', abbreviation: 'HTU', domain: 'htu.edu.gh', country: 'Ghana', city: 'Ho', type: 'Technical University', verified: true },
    { name: 'Koforidua Technical University', abbreviation: 'KTU', domain: 'ktu.edu.gh', country: 'Ghana', city: 'Koforidua', type: 'Technical University', verified: true },
    { name: 'Kumasi Technical University', abbreviation: 'KsTU', domain: 'kstu.edu.gh', country: 'Ghana', city: 'Kumasi', type: 'Technical University', verified: true },
    { name: 'Sunyani Technical University', abbreviation: 'STU', domain: 'stu.edu.gh', country: 'Ghana', city: 'Sunyani', type: 'Technical University', verified: true },
    { name: 'Takoradi Technical University', abbreviation: 'TTU', domain: 'ttu.edu.gh', country: 'Ghana', city: 'Takoradi', type: 'Technical University', verified: true },
    { name: 'Tamale Technical University', abbreviation: 'TATU', domain: 'tatu.edu.gh', country: 'Ghana', city: 'Tamale', type: 'Technical University', verified: true },
    { name: 'Akenten Appiah-Menka University of Skills Training and Entrepreneurial Development', abbreviation: 'AAM-USTED', domain: 'aamusted.edu.gh', country: 'Ghana', city: 'Kumasi', type: 'Public University', verified: true },
    { name: 'C.K. Tedam University of Technology and Applied Sciences', abbreviation: 'CKT-UTAS', domain: 'cktutas.edu.gh', country: 'Ghana', city: 'Navrongo', type: 'Public University', verified: true },
    { name: 'Ghana Communication Technology University', abbreviation: 'GCTU', domain: 'gctu.edu.gh', country: 'Ghana', city: 'Accra', type: 'Public University', verified: true },
    { name: 'Ghana Institute of Management and Public Administration', abbreviation: 'GIMPA', domain: 'gimpa.edu.gh', country: 'Ghana', city: 'Accra', type: 'Public University', verified: true },
    { name: 'Kwame Nkrumah University of Science and Technology', abbreviation: 'KNUST', domain: 'knust.edu.gh', country: 'Ghana', city: 'Kumasi', type: 'Public University', verified: true },
    { name: 'Simon Diedong Dombo University of Business and Integrated Development Studies', abbreviation: 'SDD-UBIDS', domain: 'ubids.edu.gh', country: 'Ghana', city: 'Wa', type: 'Public University', verified: true },
    { name: 'University for Development Studies', abbreviation: 'UDS', domain: 'uds.edu.gh', country: 'Ghana', city: 'Tamale', type: 'Public University', verified: true },
    { name: 'University of Cape Coast', abbreviation: 'UCC', domain: 'ucc.edu.gh', country: 'Ghana', city: 'Cape Coast', type: 'Public University', verified: true },
    { name: 'University of Education, Winneba', abbreviation: 'UEW', domain: 'uew.edu.gh', country: 'Ghana', city: 'Winneba', type: 'Public University', verified: true },
    { name: 'University of Energy and Natural Resources', abbreviation: 'UENR', domain: 'uenr.edu.gh', country: 'Ghana', city: 'Sunyani', type: 'Public University', verified: true },
    { name: 'University of Environment and Sustainable Development', abbreviation: 'UESD', domain: 'uesd.edu.gh', country: 'Ghana', city: 'Somanya', type: 'Public University', verified: true },
    { name: 'University of Ghana', abbreviation: 'UG', domain: 'ug.edu.gh', country: 'Ghana', city: 'Legon, Accra', type: 'Public University', verified: true },
    { name: 'University of Health and Allied Sciences', abbreviation: 'UHAS', domain: 'uhas.edu.gh', country: 'Ghana', city: 'Ho', type: 'Public University', verified: true },
    { name: 'University of Media, Arts and Communication', abbreviation: 'UniMAC', domain: 'unimac.edu.gh', country: 'Ghana', city: 'Accra', type: 'Public University', verified: true },
    { name: 'University of Mines and Technology', abbreviation: 'UMaT', domain: 'umat.edu.gh', country: 'Ghana', city: 'Tarkwa', type: 'Public University', verified: true },
    { name: 'University of Professional Studies, Accra', abbreviation: 'UPSA', domain: 'upsa.edu.gh', country: 'Ghana', city: 'Accra', type: 'Public University', verified: true }
  ];

  console.log('Inserting', institutions.length, 'institutions...');
  const { data, error } = await supabase.from('institutions').insert(institutions).select();
  
  if (error) {
    console.error('Insertion error:', error);
  } else {
    console.log('Successfully inserted', data.length, 'rows!');
  }
}

seedInstitutions();
