import json
import os

batch5 = [
    {"programme": "BSc Business Administration", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Accounting", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Banking and Finance", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Marketing", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Human Resource Management", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc International Business", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Logistics and Supply Chain Management", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Entrepreneurship", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Procurement and Supply Chain Management", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Operations Management", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Risk Management and Insurance", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Actuarial Science", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Economics", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Statistics", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Mathematics", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Financial Economics", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Agribusiness Management", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Hospitality and Tourism Management", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Event Management", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Real Estate Management", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Project Management", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Business Information Systems", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc E-Commerce", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Digital Marketing", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Brand Management", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Customer Relationship Management", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Retail Management", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Sales Management", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Export and Import Management", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Trade and Investment", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Development Economics", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Environmental Economics", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Economics", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Resource Economics", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Health Economics", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Labour Economics", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Transport Economics", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Urban Economics", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Demography", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Econometrics", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Applied Statistics", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Biostatistics", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Financial Mathematics", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Industrial Mathematics", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Computational Mathematics", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Applied Mathematics", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Pure Mathematics", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Mathematical Biology", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Mathematical Physics", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Mathematical Economics", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Mathematical Finance", "field": "Business, Management & Administration", "level": "Undergraduate"},
    {"programme": "BSc Mathematical Statistics", "field": "Business, Management & Administration", "level": "Undergraduate"},
]

batch9 = [
    {"programme": "BSc Agriculture", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Science", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Animal Science", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Animal Production", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Animal Health", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Animal Nutrition", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Animal Breeding and Genetics", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Animal Physiology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Animal Behaviour", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Animal Welfare", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Animal Husbandry", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Livestock Production", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Poultry Science", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Aquaculture", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Fisheries Science", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Fish Science", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Marine Fisheries", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Inland Fisheries", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Fish Processing Technology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Crop Science", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Crop Production", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Crop Protection", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Crop Physiology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Crop Breeding", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Crop Genetics", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Crop Biotechnology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Crop Ecology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Crop Pathology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Crop Entomology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Crop Nematology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Crop Virology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Crop Mycology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Crop Bacteriology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Horticulture", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Ornamental Horticulture", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Landscape Horticulture", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Olericulture", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Pomology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Floriculture", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Viticulture", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Post-Harvest Technology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Soil Science", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Soil Chemistry", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Soil Physics", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Soil Biology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Soil Microbiology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Soil Fertility", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Soil Conservation", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Soil Survey", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Soil Classification", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Soil Genesis", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Soil Mineralogy", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Soil Pedology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Soil Edaphology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agronomy", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Weed Science", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Plant Pathology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Plant Virology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Plant Nematology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Plant Entomology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Plant Mycology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Plant Bacteriology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Extension", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Rural Development", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Communication", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Education", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Engineering", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Mechanization", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Farm Machinery", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Irrigation Technology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Drainage Engineering", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Water Management", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Meteorology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Climatology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Biotechnology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Genetics", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Microbiology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Biochemistry", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Economics", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Policy", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Finance", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Marketing", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Trade", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Cooperatives", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Statistics", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Informatics", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Precision Agriculture", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Smart Agriculture", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Digital Agriculture", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Climate-Smart Agriculture", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Conservation Agriculture", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Sustainable Agriculture", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Organic Agriculture", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agroecology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agroforestry", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Silviculture", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Forest Management", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Forest Ecology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Forest Conservation", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Forest Genetics", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Forest Pathology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Forest Entomology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Forest Products", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Wood Science", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Wood Technology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Timber Engineering", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Pulp and Paper Technology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Forest Policy", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Forest Economics", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Wildlife Management", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Wildlife Ecology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Wildlife Conservation", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Wildlife Biology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Wildlife Health", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Wildlife Veterinary Science", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Range Management", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Pasture Science", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Grassland Science", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Rangeland Ecology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Natural Resource Management", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Environmental Resource Management", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Water Resource Management", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Land Resource Management", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Coastal Resource Management", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Marine Resource Management", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Biodiversity Conservation", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Ecosystem Management", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Wetland Management", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Mangrove Management", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Watershed Management", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Catchment Management", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Land Use Planning", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Rural Planning", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Community Development", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Rural Sociology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Sociology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Food Science", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Food Technology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Food Processing", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Food Engineering", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Food Microbiology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Food Chemistry", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Food Biochemistry", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Food Nutrition", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Food Safety", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Food Quality Assurance", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Food Packaging", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Food Preservation", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Food Product Development", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Food Sensory Science", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Food Rheology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Food Toxicology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Nutrition Science", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Human Nutrition", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Community Nutrition", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Clinical Nutrition", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Public Health Nutrition", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Sports Nutrition", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Animal Nutrition", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Pet Nutrition", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Aquatic Nutrition", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Biotechnology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Plant Biotechnology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Animal Biotechnology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Microbial Biotechnology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Industrial Biotechnology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Environmental Biotechnology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Marine Biotechnology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Molecular Biotechnology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Genomics", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Proteomics", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Metabolomics", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Transcriptomics", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Phenomics", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Bioinformatics", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Computational Biology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Informatics", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Biostatistics", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Statistics", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Experimental Design", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Sampling Theory", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Modelling", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Simulation Modelling", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Systems Analysis", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Operations Research", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Decision Science", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Geography", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural History", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Anthropology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Philosophy", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Ethics", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Law", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Policy", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Governance", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Administration", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Leadership", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Entrepreneurship", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Innovation", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Technology Transfer", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Knowledge Management", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Communication Technology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Media", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Journalism", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Public Relations", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Advocacy", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Diplomacy", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Negotiation", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Conflict Resolution", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Peacebuilding", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Security", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Risk Management", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Insurance", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Finance", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Investment", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Banking", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Credit", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Microfinance", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Development", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Project Management", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Programme Evaluation", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Impact Assessment", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Monitoring and Evaluation", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Gender Studies", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Youth Studies", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Indigenous Knowledge", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Traditional Knowledge", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Cultural Heritage", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Archaeology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
    {"programme": "BSc Agricultural Palaeontology", "field": "Agriculture, Forestry & Natural Resources", "level": "Undergraduate"},
]

batch6 = [
    {"programme": "MBA", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "EMBA Executive Master of Business Administration", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Finance", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Accounting", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Marketing", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Human Resource Management", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc International Business", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Entrepreneurship", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Supply Chain Management", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Project Management", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Development Finance", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Business Analytics", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Business Intelligence and Analytics", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Forensic Accounting and Fraud Examination", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Public Financial Administration", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Health Services Management", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Hospitality and Tourism Management", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Agricultural Economics", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Environmental Economics", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Development Economics", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Energy Economics", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Transport Economics", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Urban Economics", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Labour Economics", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Health Economics", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Resource Economics", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Financial Economics", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc International Economics", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Trade and Investment", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Export and Import Management", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Risk Management and Insurance", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Actuarial Science", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Statistics", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Applied Statistics", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Biostatistics", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Financial Mathematics", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Computational Mathematics", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Industrial Mathematics", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Mathematical Biology", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Mathematical Physics", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Mathematical Economics", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Mathematical Finance", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MSc Mathematical Statistics", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MPhil Business Administration", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MPhil Economics", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "MPhil Statistics", "field": "Business, Management & Administration", "level": "Postgraduate"},
    {"programme": "PhD Business Administration", "field": "Business, Management & Administration", "level": "Graduate"},
    {"programme": "PhD Economics", "field": "Business, Management & Administration", "level": "Graduate"},
    {"programme": "PhD Finance", "field": "Business, Management & Administration", "level": "Graduate"},
    {"programme": "PhD Accounting", "field": "Business, Management & Administration", "level": "Graduate"},
    {"programme": "PhD Marketing", "field": "Business, Management & Administration", "level": "Graduate"},
    {"programme": "PhD Human Resource Management", "field": "Business, Management & Administration", "level": "Graduate"}
]

all_batches = batch5 + batch9 + batch6

sql = """-- Migration: Insert missing programmes (Batches 5, 9, 6)
BEGIN;

-- Add unique constraint if not exists (Postgres 11+ syntax or standard constraint)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'course_programmes_name_key') THEN
        -- Remove duplicates before adding the unique constraint
        DELETE FROM public.course_programmes a USING public.course_programmes b WHERE a.ctid < b.ctid AND a.name = b.name;
        
        ALTER TABLE public.course_programmes ADD CONSTRAINT course_programmes_name_key UNIQUE (name);
    END IF;
END $$;

INSERT INTO public.course_programmes (name, field, level) VALUES
"""

values = []
for p in all_batches:
    prog = p['programme'].replace("'", "''")
    field = p['field'].replace("'", "''")
    level = p['level'].replace("'", "''")
    values.append(f"('{prog}', '{field}', '{level}')")

sql += ",\n".join(values)
sql += "\nON CONFLICT (name) DO NOTHING;\n\nCOMMIT;\n"

with open('supabase/migrations/20240726_insert_missing_programmes.sql', 'w', encoding='utf-8') as f:
    f.write(sql)

print(f"Generated 20240726_insert_missing_programmes.sql with {len(all_batches)} records.")
