-- Migration: Insert all programmes
-- Organized by Batches as requested.

BEGIN;

-- Add unique constraint if not exists (Postgres 11+ syntax or standard constraint)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'course_programmes_name_key') THEN
        -- Remove duplicates before adding the unique constraint
        DELETE FROM public.course_programmes a USING public.course_programmes b WHERE a.ctid < b.ctid AND a.name = b.name;
        
        ALTER TABLE public.course_programmes ADD CONSTRAINT course_programmes_name_key UNIQUE (name);
    END IF;
END $$;

INSERT INTO public.course_programmes (name, field, level) VALUES

-- BATCH 1: ENGINEERING & TECHNOLOGY
('BSc Aerospace Engineering', 'Engineering & Technology', 'Undergraduate'),
('BSc Agricultural Engineering', 'Engineering & Technology', 'Undergraduate'),
('BSc Architecture', 'Engineering & Technology', 'Undergraduate'),
('BSc Automobile Engineering', 'Engineering & Technology', 'Undergraduate'),
('BSc Biomedical Engineering', 'Engineering & Technology', 'Undergraduate'),
('BSc Chemical Engineering', 'Engineering & Technology', 'Undergraduate'),
('BSc Civil Engineering', 'Engineering & Technology', 'Undergraduate'),
('BSc Computer Engineering', 'Engineering & Technology', 'Undergraduate'),
('BSc Construction Technology and Management', 'Engineering & Technology', 'Undergraduate'),
('BSc Development Planning', 'Engineering & Technology', 'Undergraduate'),
('BSc Electrical/Electronic Engineering', 'Engineering & Technology', 'Undergraduate'),
('BSc Food Process Engineering', 'Engineering & Technology', 'Undergraduate'),
('BSc Geological Engineering', 'Engineering & Technology', 'Undergraduate'),
('BSc Geomatic Engineering', 'Engineering & Technology', 'Undergraduate'),
('BSc Human Settlement Planning', 'Engineering & Technology', 'Undergraduate'),
('BSc Industrial Engineering', 'Engineering & Technology', 'Undergraduate'),
('BSc Land Economy', 'Engineering & Technology', 'Undergraduate'),
('BSc Marine Engineering', 'Engineering & Technology', 'Undergraduate'),
('BSc Materials Engineering', 'Engineering & Technology', 'Undergraduate'),
('BSc Mechanical Engineering', 'Engineering & Technology', 'Undergraduate'),
('BSc Metallurgical Engineering', 'Engineering & Technology', 'Undergraduate'),
('BSc Petrochemical Engineering', 'Engineering & Technology', 'Undergraduate'),
('BSc Petroleum Engineering', 'Engineering & Technology', 'Undergraduate'),
('BSc Quantity Surveying and Construction Economics', 'Engineering & Technology', 'Undergraduate'),
('BSc Real Estate', 'Engineering & Technology', 'Undergraduate'),
('BSc Telecommunication Engineering', 'Engineering & Technology', 'Undergraduate'),
('PhD Engineering', 'Engineering & Technology', 'Graduate'),
('MPhil Engineering', 'Engineering & Technology', 'Postgraduate'),
('MSc Aerospace Engineering', 'Engineering & Technology', 'Postgraduate'),
('MSc Chemical Engineering', 'Engineering & Technology', 'Postgraduate'),
('MSc Civil Engineering', 'Engineering & Technology', 'Postgraduate'),
('MSc Electrical Engineering', 'Engineering & Technology', 'Postgraduate'),
('MSc Environmental Engineering', 'Engineering & Technology', 'Postgraduate'),
('MSc Geomatic Engineering', 'Engineering & Technology', 'Postgraduate'),
('MSc Geotechnical Engineering', 'Engineering & Technology', 'Postgraduate'),
('MSc Mechanical Engineering', 'Engineering & Technology', 'Postgraduate'),
('MSc Petroleum Engineering', 'Engineering & Technology', 'Postgraduate'),
('MSc Renewable Energy Engineering', 'Engineering & Technology', 'Postgraduate'),
('MSc Structural Engineering', 'Engineering & Technology', 'Postgraduate'),
('MSc Transportation Engineering', 'Engineering & Technology', 'Postgraduate'),
('MSc Water Resources Engineering', 'Engineering & Technology', 'Postgraduate'),

-- BATCH 2: INFORMATION TECHNOLOGY & COMPUTING
('BSc Artificial Intelligence', 'Information Technology & Computing', 'Undergraduate'),
('BSc Bioinformatics', 'Information Technology & Computing', 'Undergraduate'),
('BSc Blockchain Technology', 'Information Technology & Computing', 'Undergraduate'),
('BSc Business Information Technology', 'Information Technology & Computing', 'Undergraduate'),
('BSc Computational Biology', 'Information Technology & Computing', 'Undergraduate'),
('BSc Computational Linguistics', 'Information Technology & Computing', 'Undergraduate'),
('BSc Computer Animation', 'Information Technology & Computing', 'Undergraduate'),
('BSc Computer Science', 'Information Technology & Computing', 'Undergraduate'),
('BSc Cyber Security', 'Information Technology & Computing', 'Undergraduate'),
('BSc Data Engineering', 'Information Technology & Computing', 'Undergraduate'),
('BSc Data Science', 'Information Technology & Computing', 'Undergraduate'),
('BSc Database Administration', 'Information Technology & Computing', 'Undergraduate'),
('BSc DevOps Engineering', 'Information Technology & Computing', 'Undergraduate'),
('BSc Digital Media Technology', 'Information Technology & Computing', 'Undergraduate'),
('BSc Ethical Hacking', 'Information Technology & Computing', 'Undergraduate'),
('BSc Game Development', 'Information Technology & Computing', 'Undergraduate'),
('BSc Geographic Information Systems', 'Information Technology & Computing', 'Undergraduate'),
('BSc Human-Computer Interaction', 'Information Technology & Computing', 'Undergraduate'),
('BSc IT Project Management', 'Information Technology & Computing', 'Undergraduate'),
('BSc Information Technology', 'Information Technology & Computing', 'Undergraduate'),
('BSc Internet of Things (IoT)', 'Information Technology & Computing', 'Undergraduate'),
('BSc Management Information Systems', 'Information Technology & Computing', 'Undergraduate'),
('BSc Mobile Application Development', 'Information Technology & Computing', 'Undergraduate'),
('BSc Multimedia Technology', 'Information Technology & Computing', 'Undergraduate'),
('BSc Network Security', 'Information Technology & Computing', 'Undergraduate'),
('BSc Networking and Systems Administration', 'Information Technology & Computing', 'Undergraduate'),
('BSc Remote Sensing', 'Information Technology & Computing', 'Undergraduate'),
('BSc Robotics and Automation', 'Information Technology & Computing', 'Undergraduate'),
('BSc Software Engineering', 'Information Technology & Computing', 'Undergraduate'),
('BSc Virtual Reality and Augmented Reality', 'Information Technology & Computing', 'Undergraduate'),
('BSc Web Development', 'Information Technology & Computing', 'Undergraduate'),
('PhD Artificial Intelligence', 'Information Technology & Computing', 'Graduate'),
('PhD Bioinformatics', 'Information Technology & Computing', 'Graduate'),
('PhD Computational Biology', 'Information Technology & Computing', 'Graduate'),
('PhD Computer Science', 'Information Technology & Computing', 'Graduate'),
('PhD Cyber Security', 'Information Technology & Computing', 'Graduate'),
('PhD Data Science', 'Information Technology & Computing', 'Graduate'),
('PhD Geographic Information Science', 'Information Technology & Computing', 'Graduate'),
('PhD Human-Computer Interaction', 'Information Technology & Computing', 'Graduate'),
('PhD Information Technology', 'Information Technology & Computing', 'Graduate'),
('PhD Machine Learning', 'Information Technology & Computing', 'Graduate'),
('PhD Robotics', 'Information Technology & Computing', 'Graduate'),
('PhD Software Engineering', 'Information Technology & Computing', 'Graduate'),
('MPhil Computer Science', 'Information Technology & Computing', 'Postgraduate'),
('MSc Artificial Intelligence', 'Information Technology & Computing', 'Postgraduate'),
('MSc Big Data Analytics', 'Information Technology & Computing', 'Postgraduate'),
('MSc Blockchain and Distributed Ledger Technology', 'Information Technology & Computing', 'Postgraduate'),
('MSc Business Intelligence', 'Information Technology & Computing', 'Postgraduate'),
('MSc Cloud Computing', 'Information Technology & Computing', 'Postgraduate'),
('MSc Computational Neuroscience', 'Information Technology & Computing', 'Postgraduate'),
('MSc Computer Science', 'Information Technology & Computing', 'Postgraduate'),
('MSc Computer Vision', 'Information Technology & Computing', 'Postgraduate'),
('MSc Cyber Security', 'Information Technology & Computing', 'Postgraduate'),
('MSc Data Science and Analytics', 'Information Technology & Computing', 'Postgraduate'),
('MSc Deep Learning', 'Information Technology & Computing', 'Postgraduate'),
('MSc Digital Forensics', 'Information Technology & Computing', 'Postgraduate'),
('MSc Digital Transformation', 'Information Technology & Computing', 'Postgraduate'),
('MSc E-Government', 'Information Technology & Computing', 'Postgraduate'),
('MSc Educational Technology', 'Information Technology & Computing', 'Postgraduate'),
('MSc Enterprise Architecture', 'Information Technology & Computing', 'Postgraduate'),
('MSc Financial Technology (FinTech)', 'Information Technology & Computing', 'Postgraduate'),
('MSc Game Design and Development', 'Information Technology & Computing', 'Postgraduate'),
('MSc IT Governance', 'Information Technology & Computing', 'Postgraduate'),
('MSc IT Service Management', 'Information Technology & Computing', 'Postgraduate'),
('MSc Information Systems Management', 'Information Technology & Computing', 'Postgraduate'),
('MSc Information Technology', 'Information Technology & Computing', 'Postgraduate'),
('MSc Innovation and Technology Management', 'Information Technology & Computing', 'Postgraduate'),
('MSc Internet of Things', 'Information Technology & Computing', 'Postgraduate'),
('MSc Machine Learning', 'Information Technology & Computing', 'Postgraduate'),
('MSc Mobile Computing', 'Information Technology & Computing', 'Postgraduate'),
('MSc Natural Language Processing', 'Information Technology & Computing', 'Postgraduate'),
('MSc Neural Networks', 'Information Technology & Computing', 'Postgraduate'),
('MSc Quantum Computing', 'Information Technology & Computing', 'Postgraduate'),
('MSc Reinforcement Learning', 'Information Technology & Computing', 'Postgraduate'),
('MSc Robotics', 'Information Technology & Computing', 'Postgraduate'),
('MSc Software Engineering', 'Information Technology & Computing', 'Postgraduate'),
('MSc Technology Management', 'Information Technology & Computing', 'Postgraduate'),
('MSc Web Science', 'Information Technology & Computing', 'Postgraduate'),

-- BATCH 3: HEALTH SCIENCES
('BDS Bachelor of Dental Surgery', 'Health Sciences', 'Undergraduate'),
('BSc Anaesthesia', 'Health Sciences', 'Undergraduate'),
('BSc Biomedical Science', 'Health Sciences', 'Undergraduate'),
('BSc Clinical Medicine', 'Health Sciences', 'Undergraduate'),
('BSc Community Health Nursing', 'Health Sciences', 'Undergraduate'),
('BSc Critical Care Nursing', 'Health Sciences', 'Undergraduate'),
('BSc Dental Laboratory Sciences', 'Health Sciences', 'Undergraduate'),
('BSc Dietetics', 'Health Sciences', 'Undergraduate'),
('BSc Disability and Rehabilitation Studies', 'Health Sciences', 'Undergraduate'),
('BSc Emergency Nursing', 'Health Sciences', 'Undergraduate'),
('BSc Environmental Health', 'Health Sciences', 'Undergraduate'),
('BSc Health Information Management', 'Health Sciences', 'Undergraduate'),
('BSc Herbal Medicine', 'Health Sciences', 'Undergraduate'),
('BSc Human Biology (Medicine)', 'Health Sciences', 'Undergraduate'),
('BSc Medical Imaging (Radiography)', 'Health Sciences', 'Undergraduate'),
('BSc Medical Laboratory Science', 'Health Sciences', 'Undergraduate'),
('BSc Medical Sonography', 'Health Sciences', 'Undergraduate'),
('BSc Midwifery', 'Health Sciences', 'Undergraduate'),
('BSc Nursing', 'Health Sciences', 'Undergraduate'),
('BSc Nutrition and Food Science', 'Health Sciences', 'Undergraduate'),
('BSc Occupational Therapy', 'Health Sciences', 'Undergraduate'),
('BSc Peri-Operative Nursing', 'Health Sciences', 'Undergraduate'),
('BSc Pharmacy', 'Health Sciences', 'Undergraduate'),
('BSc Physician Assistantship', 'Health Sciences', 'Undergraduate'),
('BSc Physiotherapy and Sports Science', 'Health Sciences', 'Undergraduate'),
('BSc Psychiatric Nursing', 'Health Sciences', 'Undergraduate'),
('BSc Public Health', 'Health Sciences', 'Undergraduate'),
('BSc Sonography', 'Health Sciences', 'Undergraduate'),
('Doctor of Optometry (OD)', 'Health Sciences', 'Undergraduate'),
('Doctor of Pharmacy (PharmD)', 'Health Sciences', 'Undergraduate'),
('Doctor of Veterinary Medicine (DVM)', 'Health Sciences', 'Undergraduate'),
('MBChB Bachelor of Medicine and Bachelor of Surgery', 'Health Sciences', 'Undergraduate'),
('PhD Nursing', 'Health Sciences', 'Graduate'),
('PhD Public Health', 'Health Sciences', 'Graduate'),
('MPhil Nursing', 'Health Sciences', 'Postgraduate'),
('MPhil Public Health', 'Health Sciences', 'Postgraduate'),
('MSc Animal Health', 'Health Sciences', 'Postgraduate'),
('MSc Audiology', 'Health Sciences', 'Postgraduate'),
('MSc Biomedical Engineering', 'Health Sciences', 'Postgraduate'),
('MSc Chemical Pathology', 'Health Sciences', 'Postgraduate'),
('MSc Clinical Pharmacy', 'Health Sciences', 'Postgraduate'),
('MSc Clinical Psychology', 'Health Sciences', 'Postgraduate'),
('MSc Clinical Research', 'Health Sciences', 'Postgraduate'),
('MSc Community Dentistry', 'Health Sciences', 'Postgraduate'),
('MSc Counselling Psychology', 'Health Sciences', 'Postgraduate'),
('MSc Dental Public Health', 'Health Sciences', 'Postgraduate'),
('MSc Dental Surgery', 'Health Sciences', 'Postgraduate'),
('MSc Disaster Management', 'Health Sciences', 'Postgraduate'),
('MSc Endodontics', 'Health Sciences', 'Postgraduate'),
('MSc Environmental Health', 'Health Sciences', 'Postgraduate'),
('MSc Epidemiology', 'Health Sciences', 'Postgraduate'),
('MSc Exercise Physiology', 'Health Sciences', 'Postgraduate'),
('MSc Forensic Science', 'Health Sciences', 'Postgraduate'),
('MSc Global Health', 'Health Sciences', 'Postgraduate'),
('MSc Haematology and Blood Transfusion', 'Health Sciences', 'Postgraduate'),
('MSc Health Informatics', 'Health Sciences', 'Postgraduate'),
('MSc Health Policy and Management', 'Health Sciences', 'Postgraduate'),
('MSc Health Promotion', 'Health Sciences', 'Postgraduate'),
('MSc Health Psychology', 'Health Sciences', 'Postgraduate'),
('MSc Health Systems Strengthening', 'Health Sciences', 'Postgraduate'),
('MSc Histopathology', 'Health Sciences', 'Postgraduate'),
('MSc Immunology', 'Health Sciences', 'Postgraduate'),
('MSc Medical Biochemistry', 'Health Sciences', 'Postgraduate'),
('MSc Medical Laboratory Science', 'Health Sciences', 'Postgraduate'),
('MSc Medical Microbiology', 'Health Sciences', 'Postgraduate'),
('MSc Medical Parasitology', 'Health Sciences', 'Postgraduate'),
('MSc Medical Virology', 'Health Sciences', 'Postgraduate'),
('MSc Mental Health', 'Health Sciences', 'Postgraduate'),
('MSc Microbiology and Infection Control', 'Health Sciences', 'Postgraduate'),
('MSc Midwifery', 'Health Sciences', 'Postgraduate'),
('MSc Molecular Medicine', 'Health Sciences', 'Postgraduate'),
('MSc Nursing', 'Health Sciences', 'Postgraduate'),
('MSc Occupational Therapy', 'Health Sciences', 'Postgraduate'),
('MSc Optometry', 'Health Sciences', 'Postgraduate'),
('MSc Oral Medicine', 'Health Sciences', 'Postgraduate'),
('MSc Oral Pathology', 'Health Sciences', 'Postgraduate'),
('MSc Oral and Maxillofacial Surgery', 'Health Sciences', 'Postgraduate'),
('MSc Orthodontics', 'Health Sciences', 'Postgraduate'),
('MSc Orthoptics', 'Health Sciences', 'Postgraduate'),
('MSc Paediatric Dentistry', 'Health Sciences', 'Postgraduate'),
('MSc Periodontology', 'Health Sciences', 'Postgraduate'),
('MSc Pharmaceutical Sciences', 'Health Sciences', 'Postgraduate'),
('MSc Pharmacology', 'Health Sciences', 'Postgraduate'),
('MSc Physiotherapy', 'Health Sciences', 'Postgraduate'),
('MSc Prosthetics and Orthotics', 'Health Sciences', 'Postgraduate'),
('MSc Public Health', 'Health Sciences', 'Postgraduate'),
('MSc Rehabilitation Science', 'Health Sciences', 'Postgraduate'),
('MSc Reproductive Health', 'Health Sciences', 'Postgraduate'),
('MSc Restorative Dentistry', 'Health Sciences', 'Postgraduate'),
('MSc Speech and Language Therapy', 'Health Sciences', 'Postgraduate'),
('MSc Sports Medicine', 'Health Sciences', 'Postgraduate'),
('MSc Toxicology', 'Health Sciences', 'Postgraduate'),
('MSc Tropical Medicine', 'Health Sciences', 'Postgraduate'),
('MSc Veterinary Medicine', 'Health Sciences', 'Postgraduate'),
('MSc Veterinary Microbiology', 'Health Sciences', 'Postgraduate'),
('MSc Veterinary Parasitology', 'Health Sciences', 'Postgraduate'),
('MSc Veterinary Pathology', 'Health Sciences', 'Postgraduate'),
('MSc Veterinary Public Health', 'Health Sciences', 'Postgraduate'),
('MSc Veterinary Surgery', 'Health Sciences', 'Postgraduate'),
('MSc Wildlife Health', 'Health Sciences', 'Postgraduate'),

-- BATCH 4: BUSINESS, MANAGEMENT & ADMINISTRATION
('BSc Accounting', 'Business, Management & Administration', 'Undergraduate'),
('BSc Actuarial Science', 'Business, Management & Administration', 'Undergraduate'),
('BSc Agribusiness Management', 'Business, Management & Administration', 'Undergraduate'),
('BSc Agricultural Economics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Applied Mathematics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Applied Statistics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Banking and Finance', 'Business, Management & Administration', 'Undergraduate'),
('BSc Biostatistics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Brand Management', 'Business, Management & Administration', 'Undergraduate'),
('BSc Business Administration', 'Business, Management & Administration', 'Undergraduate'),
('BSc Business Information Systems', 'Business, Management & Administration', 'Undergraduate'),
('BSc Computational Mathematics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Customer Relationship Management', 'Business, Management & Administration', 'Undergraduate'),
('BSc Demography', 'Business, Management & Administration', 'Undergraduate'),
('BSc Development Economics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Digital Marketing', 'Business, Management & Administration', 'Undergraduate'),
('BSc E-Commerce', 'Business, Management & Administration', 'Undergraduate'),
('BSc Econometrics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Economics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Entrepreneurship', 'Business, Management & Administration', 'Undergraduate'),
('BSc Environmental Economics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Event Management', 'Business, Management & Administration', 'Undergraduate'),
('BSc Export and Import Management', 'Business, Management & Administration', 'Undergraduate'),
('BSc Financial Economics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Financial Mathematics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Health Economics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Hospitality and Tourism Management', 'Business, Management & Administration', 'Undergraduate'),
('BSc Human Resource Management', 'Business, Management & Administration', 'Undergraduate'),
('BSc Industrial Mathematics', 'Business, Management & Administration', 'Undergraduate'),
('BSc International Business', 'Business, Management & Administration', 'Undergraduate'),
('BSc Labour Economics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Logistics and Supply Chain Management', 'Business, Management & Administration', 'Undergraduate'),
('BSc Marketing', 'Business, Management & Administration', 'Undergraduate'),
('BSc Mathematical Biology', 'Business, Management & Administration', 'Undergraduate'),
('BSc Mathematical Economics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Mathematical Finance', 'Business, Management & Administration', 'Undergraduate'),
('BSc Mathematical Physics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Mathematical Statistics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Mathematics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Operations Management', 'Business, Management & Administration', 'Undergraduate'),
('BSc Procurement and Supply Chain Management', 'Business, Management & Administration', 'Undergraduate'),
('BSc Project Management', 'Business, Management & Administration', 'Undergraduate'),
('BSc Pure Mathematics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Real Estate Management', 'Business, Management & Administration', 'Undergraduate'),
('BSc Resource Economics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Retail Management', 'Business, Management & Administration', 'Undergraduate'),
('BSc Risk Management and Insurance', 'Business, Management & Administration', 'Undergraduate'),
('BSc Sales Management', 'Business, Management & Administration', 'Undergraduate'),
('BSc Statistics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Trade and Investment', 'Business, Management & Administration', 'Undergraduate'),
('BSc Transport Economics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Urban Economics', 'Business, Management & Administration', 'Undergraduate'),
('DBA Doctor of Business Administration', 'Business, Management & Administration', 'Graduate'),
('DCom Doctor of Commerce', 'Business, Management & Administration', 'Graduate'),
('DEcon Doctor of Economics', 'Business, Management & Administration', 'Graduate'),
('DMath Doctor of Mathematics', 'Business, Management & Administration', 'Graduate'),
('DPhil Doctor of Philosophy in Business', 'Business, Management & Administration', 'Graduate'),
('DSc Doctor of Science in Business', 'Business, Management & Administration', 'Graduate'),
('DStat Doctor of Statistics', 'Business, Management & Administration', 'Graduate'),
('PhD Accounting', 'Business, Management & Administration', 'Graduate'),
('PhD Actuarial Science', 'Business, Management & Administration', 'Graduate'),
('PhD Agricultural Economics', 'Business, Management & Administration', 'Graduate'),
('PhD Applied Statistics', 'Business, Management & Administration', 'Graduate'),
('PhD Biostatistics', 'Business, Management & Administration', 'Graduate'),
('PhD Business Administration', 'Business, Management & Administration', 'Graduate'),
('PhD Business Analytics', 'Business, Management & Administration', 'Graduate'),
('PhD Computational Mathematics', 'Business, Management & Administration', 'Graduate'),
('PhD Development Economics', 'Business, Management & Administration', 'Graduate'),
('PhD Development Finance', 'Business, Management & Administration', 'Graduate'),
('PhD Economics', 'Business, Management & Administration', 'Graduate'),
('PhD Energy Economics', 'Business, Management & Administration', 'Graduate'),
('PhD Entrepreneurship', 'Business, Management & Administration', 'Graduate'),
('PhD Environmental Economics', 'Business, Management & Administration', 'Graduate'),
('PhD Export and Import Management', 'Business, Management & Administration', 'Graduate'),
('PhD Finance', 'Business, Management & Administration', 'Graduate'),
('PhD Financial Economics', 'Business, Management & Administration', 'Graduate'),
('PhD Financial Mathematics', 'Business, Management & Administration', 'Graduate'),
('PhD Health Economics', 'Business, Management & Administration', 'Graduate'),
('PhD Human Resource Management', 'Business, Management & Administration', 'Graduate'),
('PhD Industrial Mathematics', 'Business, Management & Administration', 'Graduate'),
('PhD International Business', 'Business, Management & Administration', 'Graduate'),
('PhD International Economics', 'Business, Management & Administration', 'Graduate'),
('PhD Labour Economics', 'Business, Management & Administration', 'Graduate'),
('PhD Marketing', 'Business, Management & Administration', 'Graduate'),
('PhD Mathematical Biology', 'Business, Management & Administration', 'Graduate'),
('PhD Mathematical Economics', 'Business, Management & Administration', 'Graduate'),
('PhD Mathematical Finance', 'Business, Management & Administration', 'Graduate'),
('PhD Mathematical Physics', 'Business, Management & Administration', 'Graduate'),
('PhD Mathematical Statistics', 'Business, Management & Administration', 'Graduate'),
('PhD Project Management', 'Business, Management & Administration', 'Graduate'),
('PhD Resource Economics', 'Business, Management & Administration', 'Graduate'),
('PhD Risk Management and Insurance', 'Business, Management & Administration', 'Graduate'),
('PhD Statistics', 'Business, Management & Administration', 'Graduate'),
('PhD Supply Chain Management', 'Business, Management & Administration', 'Graduate'),
('PhD Trade and Investment', 'Business, Management & Administration', 'Graduate'),
('PhD Transport Economics', 'Business, Management & Administration', 'Graduate'),
('PhD Urban Economics', 'Business, Management & Administration', 'Graduate'),
('EMBA Executive Master of Business Administration', 'Business, Management & Administration', 'Postgraduate'),
('MBA', 'Business, Management & Administration', 'Postgraduate'),
('MPhil Business Administration', 'Business, Management & Administration', 'Postgraduate'),
('MPhil Economics', 'Business, Management & Administration', 'Postgraduate'),
('MPhil Statistics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Accounting', 'Business, Management & Administration', 'Postgraduate'),
('MSc Actuarial Science', 'Business, Management & Administration', 'Postgraduate'),
('MSc Agricultural Economics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Applied Statistics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Biostatistics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Business Analytics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Business Intelligence and Analytics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Computational Mathematics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Development Economics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Development Finance', 'Business, Management & Administration', 'Postgraduate'),
('MSc Energy Economics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Entrepreneurship', 'Business, Management & Administration', 'Postgraduate'),
('MSc Environmental Economics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Export and Import Management', 'Business, Management & Administration', 'Postgraduate'),
('MSc Finance', 'Business, Management & Administration', 'Postgraduate'),
('MSc Financial Economics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Financial Mathematics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Forensic Accounting and Fraud Examination', 'Business, Management & Administration', 'Postgraduate'),
('MSc Health Economics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Health Services Management', 'Business, Management & Administration', 'Postgraduate'),
('MSc Hospitality and Tourism Management', 'Business, Management & Administration', 'Postgraduate'),
('MSc Human Resource Management', 'Business, Management & Administration', 'Postgraduate'),
('MSc Industrial Mathematics', 'Business, Management & Administration', 'Postgraduate'),
('MSc International Business', 'Business, Management & Administration', 'Postgraduate'),
('MSc International Economics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Labour Economics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Marketing', 'Business, Management & Administration', 'Postgraduate'),
('MSc Mathematical Biology', 'Business, Management & Administration', 'Postgraduate'),
('MSc Mathematical Economics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Mathematical Finance', 'Business, Management & Administration', 'Postgraduate'),
('MSc Mathematical Physics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Mathematical Statistics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Project Management', 'Business, Management & Administration', 'Postgraduate'),
('MSc Public Financial Administration', 'Business, Management & Administration', 'Postgraduate'),
('MSc Resource Economics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Risk Management and Insurance', 'Business, Management & Administration', 'Postgraduate'),
('MSc Statistics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Supply Chain Management', 'Business, Management & Administration', 'Postgraduate'),
('MSc Trade and Investment', 'Business, Management & Administration', 'Postgraduate'),
('MSc Transport Economics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Urban Economics', 'Business, Management & Administration', 'Postgraduate'),

-- BATCH 5: NATURAL SCIENCES
('BSc Acoustics', 'Natural Sciences', 'Undergraduate'),
('BSc Agricultural Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Analytical Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Applied Geophysics', 'Natural Sciences', 'Undergraduate'),
('BSc Astronomy', 'Natural Sciences', 'Undergraduate'),
('BSc Astrophysics', 'Natural Sciences', 'Undergraduate'),
('BSc Atmospheric Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Atmospheric Science', 'Natural Sciences', 'Undergraduate'),
('BSc Biochemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Bioinorganic Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Biology', 'Natural Sciences', 'Undergraduate'),
('BSc Biomaterials', 'Natural Sciences', 'Undergraduate'),
('BSc Biophysical Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Biophysics', 'Natural Sciences', 'Undergraduate'),
('BSc Biotechnology', 'Natural Sciences', 'Undergraduate'),
('BSc Botany', 'Natural Sciences', 'Undergraduate'),
('BSc Catalysis', 'Natural Sciences', 'Undergraduate'),
('BSc Cell Biology', 'Natural Sciences', 'Undergraduate'),
('BSc Ceramics Science', 'Natural Sciences', 'Undergraduate'),
('BSc Chemical Biology', 'Natural Sciences', 'Undergraduate'),
('BSc Chemical Kinetics', 'Natural Sciences', 'Undergraduate'),
('BSc Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Climate Science', 'Natural Sciences', 'Undergraduate'),
('BSc Colloid Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Composite Materials', 'Natural Sciences', 'Undergraduate'),
('BSc Computational Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Computational Physics', 'Natural Sciences', 'Undergraduate'),
('BSc Condensed Matter Physics', 'Natural Sciences', 'Undergraduate'),
('BSc Cosmology', 'Natural Sciences', 'Undergraduate'),
('BSc Crystallography', 'Natural Sciences', 'Undergraduate'),
('BSc Earth Science', 'Natural Sciences', 'Undergraduate'),
('BSc Economic Geology', 'Natural Sciences', 'Undergraduate'),
('BSc Electrochemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Engineering Geology', 'Natural Sciences', 'Undergraduate'),
('BSc Environmental Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Environmental Geology', 'Natural Sciences', 'Undergraduate'),
('BSc Environmental Physics', 'Natural Sciences', 'Undergraduate'),
('BSc Environmental Science', 'Natural Sciences', 'Undergraduate'),
('BSc Experimental Physics', 'Natural Sciences', 'Undergraduate'),
('BSc Exploration Geophysics', 'Natural Sciences', 'Undergraduate'),
('BSc Food Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Gemmology', 'Natural Sciences', 'Undergraduate'),
('BSc Genetics', 'Natural Sciences', 'Undergraduate'),
('BSc Genomics', 'Natural Sciences', 'Undergraduate'),
('BSc Geochemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Geology', 'Natural Sciences', 'Undergraduate'),
('BSc Geophysics', 'Natural Sciences', 'Undergraduate'),
('BSc Glass Science', 'Natural Sciences', 'Undergraduate'),
('BSc Green Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Health Physics', 'Natural Sciences', 'Undergraduate'),
('BSc Hydrogeology', 'Natural Sciences', 'Undergraduate'),
('BSc Hydrology', 'Natural Sciences', 'Undergraduate'),
('BSc Industrial Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Inorganic Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Isotope Geology', 'Natural Sciences', 'Undergraduate'),
('BSc Laser Technology', 'Natural Sciences', 'Undergraduate'),
('BSc Limnology', 'Natural Sciences', 'Undergraduate'),
('BSc Marine Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Marine Science', 'Natural Sciences', 'Undergraduate'),
('BSc Materials Science', 'Natural Sciences', 'Undergraduate'),
('BSc Medical Geology', 'Natural Sciences', 'Undergraduate'),
('BSc Medical Physics', 'Natural Sciences', 'Undergraduate'),
('BSc Medicinal Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Meteorology', 'Natural Sciences', 'Undergraduate'),
('BSc Microbiology', 'Natural Sciences', 'Undergraduate'),
('BSc Micropalaeontology', 'Natural Sciences', 'Undergraduate'),
('BSc Mineralogy', 'Natural Sciences', 'Undergraduate'),
('BSc Molecular Biology', 'Natural Sciences', 'Undergraduate'),
('BSc Nanotechnology', 'Natural Sciences', 'Undergraduate'),
('BSc Nuclear Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Nuclear Physics', 'Natural Sciences', 'Undergraduate'),
('BSc Oceanography', 'Natural Sciences', 'Undergraduate'),
('BSc Optics', 'Natural Sciences', 'Undergraduate'),
('BSc Organic Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Organometallic Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Palaeontology', 'Natural Sciences', 'Undergraduate'),
('BSc Particle Physics', 'Natural Sciences', 'Undergraduate'),
('BSc Petrology', 'Natural Sciences', 'Undergraduate'),
('BSc Pharmaceutical Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Photochemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Photonics', 'Natural Sciences', 'Undergraduate'),
('BSc Physical Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Physics', 'Natural Sciences', 'Undergraduate'),
('BSc Planetary Science', 'Natural Sciences', 'Undergraduate'),
('BSc Plasma Physics', 'Natural Sciences', 'Undergraduate'),
('BSc Polymer Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Polymer Science', 'Natural Sciences', 'Undergraduate'),
('BSc Proteomics', 'Natural Sciences', 'Undergraduate'),
('BSc Quantum Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Quantum Physics', 'Natural Sciences', 'Undergraduate'),
('BSc Radiation Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Radiation Physics', 'Natural Sciences', 'Undergraduate'),
('BSc Radio Astronomy', 'Natural Sciences', 'Undergraduate'),
('BSc Sedimentology', 'Natural Sciences', 'Undergraduate'),
('BSc Seismology', 'Natural Sciences', 'Undergraduate'),
('BSc Soil Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Solid State Physics', 'Natural Sciences', 'Undergraduate'),
('BSc Space Science', 'Natural Sciences', 'Undergraduate'),
('BSc Structural Geology', 'Natural Sciences', 'Undergraduate'),
('BSc Supramolecular Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Surface Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Theoretical Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Theoretical Physics', 'Natural Sciences', 'Undergraduate'),
('BSc Thermodynamics', 'Natural Sciences', 'Undergraduate'),
('BSc Volcanology', 'Natural Sciences', 'Undergraduate'),
('BSc Water Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Zoology', 'Natural Sciences', 'Undergraduate'),
('BStratigraphy', 'Natural Sciences', 'Undergraduate'),
('PhD Analytical Chemistry', 'Natural Sciences', 'Graduate'),
('PhD Astrophysics', 'Natural Sciences', 'Graduate'),
('PhD Biochemistry', 'Natural Sciences', 'Graduate'),
('PhD Biology', 'Natural Sciences', 'Graduate'),
('PhD Biotechnology', 'Natural Sciences', 'Graduate'),
('PhD Chemistry', 'Natural Sciences', 'Graduate'),
('PhD Computational Chemistry', 'Natural Sciences', 'Graduate'),
('PhD Environmental Science', 'Natural Sciences', 'Graduate'),
('PhD Genetics', 'Natural Sciences', 'Graduate'),
('PhD Geochemistry', 'Natural Sciences', 'Graduate'),
('PhD Geology', 'Natural Sciences', 'Graduate'),
('PhD Geophysics', 'Natural Sciences', 'Graduate'),
('PhD Marine Biology', 'Natural Sciences', 'Graduate'),
('PhD Materials Science', 'Natural Sciences', 'Graduate'),
('PhD Microbiology', 'Natural Sciences', 'Graduate'),
('PhD Molecular Biology', 'Natural Sciences', 'Graduate'),
('PhD Nanotechnology', 'Natural Sciences', 'Graduate'),
('PhD Organic Chemistry', 'Natural Sciences', 'Graduate'),
('PhD Physics', 'Natural Sciences', 'Graduate'),
('PhD Plant Biotechnology', 'Natural Sciences', 'Graduate'),
('PhD Plant Pathology', 'Natural Sciences', 'Graduate'),
('PhD Virology', 'Natural Sciences', 'Graduate'),
('MSc Analytical Chemistry', 'Natural Sciences', 'Postgraduate'),
('MSc Astrophysics', 'Natural Sciences', 'Postgraduate'),
('MSc Atmospheric Science', 'Natural Sciences', 'Postgraduate'),
('MSc Bacteriology', 'Natural Sciences', 'Postgraduate'),
('MSc Biochemistry', 'Natural Sciences', 'Postgraduate'),
('MSc Biology', 'Natural Sciences', 'Postgraduate'),
('MSc Biophysics', 'Natural Sciences', 'Postgraduate'),
('MSc Biotechnology', 'Natural Sciences', 'Postgraduate'),
('MSc Botany', 'Natural Sciences', 'Postgraduate'),
('MSc Cell Biology', 'Natural Sciences', 'Postgraduate'),
('MSc Chemistry', 'Natural Sciences', 'Postgraduate'),
('MSc Climate Science', 'Natural Sciences', 'Postgraduate'),
('MSc Computational Chemistry', 'Natural Sciences', 'Postgraduate'),
('MSc Computational Physics', 'Natural Sciences', 'Postgraduate'),
('MSc Condensed Matter Physics', 'Natural Sciences', 'Postgraduate'),
('MSc Conservation Biology', 'Natural Sciences', 'Postgraduate'),
('MSc Developmental Biology', 'Natural Sciences', 'Postgraduate'),
('MSc Earth Science', 'Natural Sciences', 'Postgraduate'),
('MSc Electrochemistry', 'Natural Sciences', 'Postgraduate'),
('MSc Engineering Geology', 'Natural Sciences', 'Postgraduate'),
('MSc Entomology', 'Natural Sciences', 'Postgraduate'),
('MSc Environmental Chemistry', 'Natural Sciences', 'Postgraduate'),
('MSc Environmental Science', 'Natural Sciences', 'Postgraduate'),
('MSc Evolutionary Biology', 'Natural Sciences', 'Postgraduate'),
('MSc Food Chemistry', 'Natural Sciences', 'Postgraduate'),
('MSc Genetics', 'Natural Sciences', 'Postgraduate'),
('MSc Genomics', 'Natural Sciences', 'Postgraduate'),
('MSc Geochemistry', 'Natural Sciences', 'Postgraduate'),
('MSc Geology', 'Natural Sciences', 'Postgraduate'),
('MSc Geophysics', 'Natural Sciences', 'Postgraduate'),
('MSc Green Chemistry', 'Natural Sciences', 'Postgraduate'),
('MSc Hydrogeology', 'Natural Sciences', 'Postgraduate'),
('MSc Hydrology', 'Natural Sciences', 'Postgraduate'),
('MSc Industrial Chemistry', 'Natural Sciences', 'Postgraduate'),
('MSc Inorganic Chemistry', 'Natural Sciences', 'Postgraduate'),
('MSc Marine Biology', 'Natural Sciences', 'Postgraduate'),
('MSc Marine Science', 'Natural Sciences', 'Postgraduate'),
('MSc Materials Science', 'Natural Sciences', 'Postgraduate'),
('MSc Medical Physics', 'Natural Sciences', 'Postgraduate'),
('MSc Medicinal Chemistry', 'Natural Sciences', 'Postgraduate'),
('MSc Meteorology', 'Natural Sciences', 'Postgraduate'),
('MSc Microbiology', 'Natural Sciences', 'Postgraduate'),
('MSc Mineralogy', 'Natural Sciences', 'Postgraduate'),
('MSc Molecular Biology', 'Natural Sciences', 'Postgraduate'),
('MSc Mycology', 'Natural Sciences', 'Postgraduate'),
('MSc Nanotechnology', 'Natural Sciences', 'Postgraduate'),
('MSc Nuclear Physics', 'Natural Sciences', 'Postgraduate'),
('MSc Oceanography', 'Natural Sciences', 'Postgraduate'),
('MSc Organic Chemistry', 'Natural Sciences', 'Postgraduate'),
('MSc Parasitology', 'Natural Sciences', 'Postgraduate'),
('MSc Petrology', 'Natural Sciences', 'Postgraduate'),
('MSc Photonics', 'Natural Sciences', 'Postgraduate'),
('MSc Physical Chemistry', 'Natural Sciences', 'Postgraduate'),
('MSc Physics', 'Natural Sciences', 'Postgraduate'),
('MSc Plant Biotechnology', 'Natural Sciences', 'Postgraduate'),
('MSc Plant Ecology', 'Natural Sciences', 'Postgraduate'),
('MSc Plant Genetics', 'Natural Sciences', 'Postgraduate'),
('MSc Plant Pathology', 'Natural Sciences', 'Postgraduate'),
('MSc Plant Physiology', 'Natural Sciences', 'Postgraduate'),
('MSc Polymer Science', 'Natural Sciences', 'Postgraduate'),
('MSc Quantum Physics', 'Natural Sciences', 'Postgraduate'),
('MSc Seismology', 'Natural Sciences', 'Postgraduate'),
('MSc Space Science', 'Natural Sciences', 'Postgraduate'),
('MSc Structural Biology', 'Natural Sciences', 'Postgraduate'),
('MSc Synthetic Biology', 'Natural Sciences', 'Postgraduate'),
('MSc Systems Biology', 'Natural Sciences', 'Postgraduate'),
('MSc Theoretical Physics', 'Natural Sciences', 'Postgraduate'),
('MSc Virology', 'Natural Sciences', 'Postgraduate'),
('MSc Wildlife Biology', 'Natural Sciences', 'Postgraduate'),
('MSc Zoology', 'Natural Sciences', 'Postgraduate'),

-- BATCH 6: SOCIAL SCIENCES
('BA African Studies', 'Social Sciences', 'Undergraduate'),
('BA Anthropology', 'Social Sciences', 'Undergraduate'),
('BA Archaeology', 'Social Sciences', 'Undergraduate'),
('BA Christian Ministry', 'Social Sciences', 'Undergraduate'),
('BA Development Studies', 'Social Sciences', 'Undergraduate'),
('BA Gender Studies', 'Social Sciences', 'Undergraduate'),
('BA Geography', 'Social Sciences', 'Undergraduate'),
('BA History', 'Social Sciences', 'Undergraduate'),
('BA International Relations', 'Social Sciences', 'Undergraduate'),
('BA Islamic Studies', 'Social Sciences', 'Undergraduate'),
('BA Philosophy', 'Social Sciences', 'Undergraduate'),
('BA Political Science', 'Social Sciences', 'Undergraduate'),
('BA Psychology', 'Social Sciences', 'Undergraduate'),
('BA Public Administration', 'Social Sciences', 'Undergraduate'),
('BA Religious Studies', 'Social Sciences', 'Undergraduate'),
('BA Social Work', 'Social Sciences', 'Undergraduate'),
('BA Sociology', 'Social Sciences', 'Undergraduate'),
('BA Theology', 'Social Sciences', 'Undergraduate')
ON CONFLICT (name) DO NOTHING;

COMMIT;
