-- Migration: Insert Batches 7 to 10
-- Adding additional programmes provided


BEGIN;

-- Add unique constraint if not exists (Postgres 11+ syntax or standard constraint)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'course_programmes_name_key') THEN
        -- Remove duplicates before adding the unique constraint
        DELETE FROM public.course_programmes a USING public.course_programmes b WHERE a.ctid < b.ctid AND a.name = b.name;
        
        ALTER TABLE public.course_programmes ADD CONSTRAINT course_programmes_name_key UNIQUE (name);
    END IF;
END $$;

INSERT INTO public.course_programmes (name, field, level) VALUES
('BSc Physics', 'Natural Sciences', 'Undergraduate'),
('BSc Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Biology', 'Natural Sciences', 'Undergraduate'),
('BSc Biochemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Microbiology', 'Natural Sciences', 'Undergraduate'),
('BSc Botany', 'Natural Sciences', 'Undergraduate'),
('BSc Zoology', 'Natural Sciences', 'Undergraduate'),
('BSc Environmental Science', 'Natural Sciences', 'Undergraduate'),
('BSc Geology', 'Natural Sciences', 'Undergraduate'),
('BSc Earth Science', 'Natural Sciences', 'Undergraduate'),
('BSc Marine Science', 'Natural Sciences', 'Undergraduate'),
('BSc Oceanography', 'Natural Sciences', 'Undergraduate'),
('BSc Meteorology', 'Natural Sciences', 'Undergraduate'),
('BSc Climate Science', 'Natural Sciences', 'Undergraduate'),
('BSc Atmospheric Science', 'Natural Sciences', 'Undergraduate'),
('BSc Hydrology', 'Natural Sciences', 'Undergraduate'),
('BSc Limnology', 'Natural Sciences', 'Undergraduate'),
('BSc Biotechnology', 'Natural Sciences', 'Undergraduate'),
('BSc Molecular Biology', 'Natural Sciences', 'Undergraduate'),
('BSc Cell Biology', 'Natural Sciences', 'Undergraduate'),
('BSc Genetics', 'Natural Sciences', 'Undergraduate'),
('BSc Genomics', 'Natural Sciences', 'Undergraduate'),
('BSc Proteomics', 'Natural Sciences', 'Undergraduate'),
('BSc Nanotechnology', 'Natural Sciences', 'Undergraduate'),
('BSc Materials Science', 'Natural Sciences', 'Undergraduate'),
('BSc Polymer Science', 'Natural Sciences', 'Undergraduate'),
('BSc Ceramics Science', 'Natural Sciences', 'Undergraduate'),
('BSc Glass Science', 'Natural Sciences', 'Undergraduate'),
('BSc Composite Materials', 'Natural Sciences', 'Undergraduate'),
('BSc Biomaterials', 'Natural Sciences', 'Undergraduate'),
('BSc Photonics', 'Natural Sciences', 'Undergraduate'),
('BSc Optics', 'Natural Sciences', 'Undergraduate'),
('BSc Laser Technology', 'Natural Sciences', 'Undergraduate'),
('BSc Quantum Physics', 'Natural Sciences', 'Undergraduate'),
('BSc Nuclear Physics', 'Natural Sciences', 'Undergraduate'),
('BSc Particle Physics', 'Natural Sciences', 'Undergraduate'),
('BSc Astrophysics', 'Natural Sciences', 'Undergraduate'),
('BSc Cosmology', 'Natural Sciences', 'Undergraduate'),
('BSc Space Science', 'Natural Sciences', 'Undergraduate'),
('BSc Planetary Science', 'Natural Sciences', 'Undergraduate'),
('BSc Astronomy', 'Natural Sciences', 'Undergraduate'),
('BSc Radio Astronomy', 'Natural Sciences', 'Undergraduate'),
('BSc Theoretical Physics', 'Natural Sciences', 'Undergraduate'),
('BSc Computational Physics', 'Natural Sciences', 'Undergraduate'),
('BSc Experimental Physics', 'Natural Sciences', 'Undergraduate'),
('BSc Condensed Matter Physics', 'Natural Sciences', 'Undergraduate'),
('BSc Solid State Physics', 'Natural Sciences', 'Undergraduate'),
('BSc Plasma Physics', 'Natural Sciences', 'Undergraduate'),
('BSc Acoustics', 'Natural Sciences', 'Undergraduate'),
('BSc Biophysics', 'Natural Sciences', 'Undergraduate'),
('BSc Medical Physics', 'Natural Sciences', 'Undergraduate'),
('BSc Health Physics', 'Natural Sciences', 'Undergraduate'),
('BSc Radiation Physics', 'Natural Sciences', 'Undergraduate'),
('BSc Environmental Physics', 'Natural Sciences', 'Undergraduate'),
('BSc Geophysics', 'Natural Sciences', 'Undergraduate'),
('BSc Exploration Geophysics', 'Natural Sciences', 'Undergraduate'),
('BSc Applied Geophysics', 'Natural Sciences', 'Undergraduate'),
('BSc Seismology', 'Natural Sciences', 'Undergraduate'),
('BSc Volcanology', 'Natural Sciences', 'Undergraduate'),
('BSc Petrology', 'Natural Sciences', 'Undergraduate'),
('BSc Mineralogy', 'Natural Sciences', 'Undergraduate'),
('BSc Crystallography', 'Natural Sciences', 'Undergraduate'),
('BSc Economic Geology', 'Natural Sciences', 'Undergraduate'),
('BSc Structural Geology', 'Natural Sciences', 'Undergraduate'),
('BSc Sedimentology', 'Natural Sciences', 'Undergraduate'),
('BStratigraphy', 'Natural Sciences', 'Undergraduate'),
('BSc Palaeontology', 'Natural Sciences', 'Undergraduate'),
('BSc Micropalaeontology', 'Natural Sciences', 'Undergraduate'),
('BSc Geochemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Isotope Geology', 'Natural Sciences', 'Undergraduate'),
('BSc Hydrogeology', 'Natural Sciences', 'Undergraduate'),
('BSc Engineering Geology', 'Natural Sciences', 'Undergraduate'),
('BSc Environmental Geology', 'Natural Sciences', 'Undergraduate'),
('BSc Medical Geology', 'Natural Sciences', 'Undergraduate'),
('BSc Gemmology', 'Natural Sciences', 'Undergraduate'),
('BSc Organic Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Inorganic Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Physical Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Analytical Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Environmental Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Medicinal Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Pharmaceutical Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Polymer Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Industrial Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Food Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Agricultural Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Soil Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Water Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Atmospheric Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Marine Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Computational Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Theoretical Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Quantum Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Electrochemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Thermodynamics', 'Natural Sciences', 'Undergraduate'),
('BSc Chemical Kinetics', 'Natural Sciences', 'Undergraduate'),
('BSc Surface Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Colloid Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Catalysis', 'Natural Sciences', 'Undergraduate'),
('BSc Photochemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Radiation Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Nuclear Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Green Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Supramolecular Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Organometallic Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Bioinorganic Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Biophysical Chemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Chemical Biology', 'Natural Sciences', 'Undergraduate'),
('BSc Synthetic Biology', 'Natural Sciences', 'Undergraduate'),
('BSc Systems Biology', 'Natural Sciences', 'Undergraduate'),
('BSc Structural Biology', 'Natural Sciences', 'Undergraduate'),
('BSc Developmental Biology', 'Natural Sciences', 'Undergraduate'),
('BSc Evolutionary Biology', 'Natural Sciences', 'Undergraduate'),
('BSc Conservation Biology', 'Natural Sciences', 'Undergraduate'),
('BSc Wildlife Biology', 'Natural Sciences', 'Undergraduate'),
('BSc Marine Biology', 'Natural Sciences', 'Undergraduate'),
('BSc Freshwater Biology', 'Natural Sciences', 'Undergraduate'),
('BSc Parasitology', 'Natural Sciences', 'Undergraduate'),
('BSc Entomology', 'Natural Sciences', 'Undergraduate'),
('BSc Nematology', 'Natural Sciences', 'Undergraduate'),
('BSc Helminthology', 'Natural Sciences', 'Undergraduate'),
('BSc Protozoology', 'Natural Sciences', 'Undergraduate'),
('BSc Mycology', 'Natural Sciences', 'Undergraduate'),
('BSc Virology', 'Natural Sciences', 'Undergraduate'),
('BSc Bacteriology', 'Natural Sciences', 'Undergraduate'),
('BSc Algology', 'Natural Sciences', 'Undergraduate'),
('BSc Bryology', 'Natural Sciences', 'Undergraduate'),
('BSc Pteridology', 'Natural Sciences', 'Undergraduate'),
('BSc Dendrology', 'Natural Sciences', 'Undergraduate'),
('BSc Ethnobotany', 'Natural Sciences', 'Undergraduate'),
('BSc Economic Botany', 'Natural Sciences', 'Undergraduate'),
('BSc Plant Pathology', 'Natural Sciences', 'Undergraduate'),
('BSc Plant Physiology', 'Natural Sciences', 'Undergraduate'),
('BSc Plant Ecology', 'Natural Sciences', 'Undergraduate'),
('BSc Plant Taxonomy', 'Natural Sciences', 'Undergraduate'),
('BSc Plant Anatomy', 'Natural Sciences', 'Undergraduate'),
('BSc Plant Morphology', 'Natural Sciences', 'Undergraduate'),
('BSc Plant Cytology', 'Natural Sciences', 'Undergraduate'),
('BSc Plant Genetics', 'Natural Sciences', 'Undergraduate'),
('BSc Plant Breeding', 'Natural Sciences', 'Undergraduate'),
('BSc Plant Biotechnology', 'Natural Sciences', 'Undergraduate'),
('BSc Plant Molecular Biology', 'Natural Sciences', 'Undergraduate'),
('BSc Plant Biochemistry', 'Natural Sciences', 'Undergraduate'),
('BSc Plant Microbiology', 'Natural Sciences', 'Undergraduate'),
('BSc Plant Virology', 'Natural Sciences', 'Undergraduate'),
('BSc Plant Nematology', 'Natural Sciences', 'Undergraduate'),
('BSc Plant Mycology', 'Natural Sciences', 'Undergraduate'),
('BSc Plant Bacteriology', 'Natural Sciences', 'Undergraduate'),
('BSc Plant Entomology', 'Natural Sciences', 'Undergraduate'),
('BSc Plant Parasitology', 'Natural Sciences', 'Undergraduate'),
('BSc Plant Virology', 'Natural Sciences', 'Undergraduate'),
('BSc Plant Nematology', 'Natural Sciences', 'Undergraduate'),
('BSc Plant Mycology', 'Natural Sciences', 'Undergraduate'),
('BSc Plant Bacteriology', 'Natural Sciences', 'Undergraduate'),
('BSc Plant Entomology', 'Natural Sciences', 'Undergraduate'),
('BSc Plant Parasitology', 'Natural Sciences', 'Undergraduate'),
('MSc Physics', 'Natural Sciences', 'Postgraduate'),
('MSc Chemistry', 'Natural Sciences', 'Postgraduate'),
('MSc Biology', 'Natural Sciences', 'Postgraduate'),
('MSc Biochemistry', 'Natural Sciences', 'Postgraduate'),
('MSc Microbiology', 'Natural Sciences', 'Postgraduate'),
('MSc Botany', 'Natural Sciences', 'Postgraduate'),
('MSc Zoology', 'Natural Sciences', 'Postgraduate'),
('MSc Environmental Science', 'Natural Sciences', 'Postgraduate'),
('MSc Geology', 'Natural Sciences', 'Postgraduate'),
('MSc Earth Science', 'Natural Sciences', 'Postgraduate'),
('MSc Marine Science', 'Natural Sciences', 'Postgraduate'),
('MSc Oceanography', 'Natural Sciences', 'Postgraduate'),
('MSc Meteorology', 'Natural Sciences', 'Postgraduate'),
('MSc Climate Science', 'Natural Sciences', 'Postgraduate'),
('MSc Atmospheric Science', 'Natural Sciences', 'Postgraduate'),
('MSc Hydrology', 'Natural Sciences', 'Postgraduate'),
('MSc Biotechnology', 'Natural Sciences', 'Postgraduate'),
('MSc Molecular Biology', 'Natural Sciences', 'Postgraduate'),
('MSc Cell Biology', 'Natural Sciences', 'Postgraduate'),
('MSc Genetics', 'Natural Sciences', 'Postgraduate'),
('MSc Genomics', 'Natural Sciences', 'Postgraduate'),
('MSc Nanotechnology', 'Natural Sciences', 'Postgraduate'),
('MSc Materials Science', 'Natural Sciences', 'Postgraduate'),
('MSc Polymer Science', 'Natural Sciences', 'Postgraduate'),
('MSc Photonics', 'Natural Sciences', 'Postgraduate'),
('MSc Quantum Physics', 'Natural Sciences', 'Postgraduate'),
('MSc Nuclear Physics', 'Natural Sciences', 'Postgraduate'),
('MSc Astrophysics', 'Natural Sciences', 'Postgraduate'),
('MSc Space Science', 'Natural Sciences', 'Postgraduate'),
('MSc Theoretical Physics', 'Natural Sciences', 'Postgraduate'),
('MSc Computational Physics', 'Natural Sciences', 'Postgraduate'),
('MSc Condensed Matter Physics', 'Natural Sciences', 'Postgraduate'),
('MSc Biophysics', 'Natural Sciences', 'Postgraduate'),
('MSc Medical Physics', 'Natural Sciences', 'Postgraduate'),
('MSc Geophysics', 'Natural Sciences', 'Postgraduate'),
('MSc Seismology', 'Natural Sciences', 'Postgraduate'),
('MSc Petrology', 'Natural Sciences', 'Postgraduate'),
('MSc Mineralogy', 'Natural Sciences', 'Postgraduate'),
('MSc Geochemistry', 'Natural Sciences', 'Postgraduate'),
('MSc Hydrogeology', 'Natural Sciences', 'Postgraduate'),
('MSc Engineering Geology', 'Natural Sciences', 'Postgraduate'),
('MSc Organic Chemistry', 'Natural Sciences', 'Postgraduate'),
('MSc Inorganic Chemistry', 'Natural Sciences', 'Postgraduate'),
('MSc Physical Chemistry', 'Natural Sciences', 'Postgraduate'),
('MSc Analytical Chemistry', 'Natural Sciences', 'Postgraduate'),
('MSc Environmental Chemistry', 'Natural Sciences', 'Postgraduate'),
('MSc Medicinal Chemistry', 'Natural Sciences', 'Postgraduate'),
('MSc Industrial Chemistry', 'Natural Sciences', 'Postgraduate'),
('MSc Food Chemistry', 'Natural Sciences', 'Postgraduate'),
('MSc Computational Chemistry', 'Natural Sciences', 'Postgraduate'),
('MSc Electrochemistry', 'Natural Sciences', 'Postgraduate'),
('MSc Green Chemistry', 'Natural Sciences', 'Postgraduate'),
('MSc Synthetic Biology', 'Natural Sciences', 'Postgraduate'),
('MSc Systems Biology', 'Natural Sciences', 'Postgraduate'),
('MSc Structural Biology', 'Natural Sciences', 'Postgraduate'),
('MSc Developmental Biology', 'Natural Sciences', 'Postgraduate'),
('MSc Evolutionary Biology', 'Natural Sciences', 'Postgraduate'),
('MSc Conservation Biology', 'Natural Sciences', 'Postgraduate'),
('MSc Wildlife Biology', 'Natural Sciences', 'Postgraduate'),
('MSc Marine Biology', 'Natural Sciences', 'Postgraduate'),
('MSc Parasitology', 'Natural Sciences', 'Postgraduate'),
('MSc Entomology', 'Natural Sciences', 'Postgraduate'),
('MSc Mycology', 'Natural Sciences', 'Postgraduate'),
('MSc Virology', 'Natural Sciences', 'Postgraduate'),
('MSc Bacteriology', 'Natural Sciences', 'Postgraduate'),
('MSc Plant Pathology', 'Natural Sciences', 'Postgraduate'),
('MSc Plant Physiology', 'Natural Sciences', 'Postgraduate'),
('MSc Plant Ecology', 'Natural Sciences', 'Postgraduate'),
('MSc Plant Genetics', 'Natural Sciences', 'Postgraduate'),
('MSc Plant Biotechnology', 'Natural Sciences', 'Postgraduate'),
('PhD Physics', 'Natural Sciences', 'Graduate'),
('PhD Chemistry', 'Natural Sciences', 'Graduate'),
('PhD Biology', 'Natural Sciences', 'Graduate'),
('PhD Biochemistry', 'Natural Sciences', 'Graduate'),
('PhD Microbiology', 'Natural Sciences', 'Graduate'),
('PhD Environmental Science', 'Natural Sciences', 'Graduate'),
('PhD Geology', 'Natural Sciences', 'Graduate'),
('PhD Biotechnology', 'Natural Sciences', 'Graduate'),
('PhD Molecular Biology', 'Natural Sciences', 'Graduate'),
('PhD Genetics', 'Natural Sciences', 'Graduate'),
('PhD Nanotechnology', 'Natural Sciences', 'Graduate'),
('PhD Materials Science', 'Natural Sciences', 'Graduate'),
('PhD Astrophysics', 'Natural Sciences', 'Graduate'),
('PhD Geophysics', 'Natural Sciences', 'Graduate'),
('PhD Geochemistry', 'Natural Sciences', 'Graduate'),
('PhD Organic Chemistry', 'Natural Sciences', 'Graduate'),
('PhD Analytical Chemistry', 'Natural Sciences', 'Graduate'),
('PhD Computational Chemistry', 'Natural Sciences', 'Graduate'),
('PhD Marine Biology', 'Natural Sciences', 'Graduate'),
('PhD Virology', 'Natural Sciences', 'Graduate'),
('PhD Plant Pathology', 'Natural Sciences', 'Graduate'),
('PhD Plant Biotechnology', 'Natural Sciences', 'Graduate'),
('BSc Agriculture', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Science', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Animal Science', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Animal Production', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Animal Health', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Animal Nutrition', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Animal Breeding and Genetics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Animal Physiology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Animal Behaviour', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Animal Welfare', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Animal Husbandry', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Livestock Production', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Poultry Science', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Aquaculture', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Fisheries Science', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Fish Science', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Marine Fisheries', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Inland Fisheries', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Fish Processing Technology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Crop Science', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Crop Production', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Crop Protection', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Crop Physiology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Crop Breeding', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Crop Genetics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Crop Biotechnology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Crop Ecology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Crop Pathology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Crop Entomology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Crop Nematology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Crop Virology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Crop Mycology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Crop Bacteriology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Horticulture', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Ornamental Horticulture', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Landscape Horticulture', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Olericulture', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Pomology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Floriculture', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Viticulture', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Post-Harvest Technology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Soil Science', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Soil Chemistry', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Soil Physics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Soil Biology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Soil Microbiology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Soil Fertility', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Soil Conservation', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Soil Survey', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Soil Classification', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Soil Genesis', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Soil Mineralogy', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Soil Pedology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Soil Edaphology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agronomy', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Weed Science', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Plant Pathology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Plant Virology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Plant Nematology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Plant Entomology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Plant Mycology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Plant Bacteriology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Extension', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Rural Development', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Communication', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Education', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Engineering', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Mechanization', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Farm Machinery', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Irrigation Technology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Drainage Engineering', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Water Management', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Meteorology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Climatology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Biotechnology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Genetics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Microbiology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Biochemistry', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Economics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Policy', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Finance', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Marketing', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Trade', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Cooperatives', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Statistics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Informatics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Precision Agriculture', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Smart Agriculture', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Digital Agriculture', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Climate-Smart Agriculture', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Conservation Agriculture', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Sustainable Agriculture', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Organic Agriculture', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agroecology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agroforestry', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Silviculture', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Forest Management', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Forest Ecology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Forest Conservation', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Forest Genetics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Forest Pathology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Forest Entomology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Forest Products', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Wood Science', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Wood Technology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Timber Engineering', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Pulp and Paper Technology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Forest Policy', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Forest Economics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Wildlife Management', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Wildlife Ecology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Wildlife Conservation', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Wildlife Biology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Wildlife Health', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Wildlife Veterinary Science', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Range Management', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Pasture Science', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Grassland Science', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Rangeland Ecology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Natural Resource Management', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Environmental Resource Management', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Water Resource Management', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Land Resource Management', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Coastal Resource Management', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Marine Resource Management', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Biodiversity Conservation', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Ecosystem Management', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Wetland Management', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Mangrove Management', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Watershed Management', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Catchment Management', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Land Use Planning', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Rural Planning', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Community Development', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Rural Sociology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Sociology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Food Science', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Food Technology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Food Processing', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Food Engineering', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Food Microbiology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Food Chemistry', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Food Biochemistry', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Food Nutrition', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Food Safety', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Food Quality Assurance', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Food Packaging', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Food Preservation', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Food Product Development', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Food Sensory Science', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Food Rheology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Food Toxicology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Nutrition Science', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Human Nutrition', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Community Nutrition', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Clinical Nutrition', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Public Health Nutrition', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Sports Nutrition', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Animal Nutrition', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Pet Nutrition', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Aquatic Nutrition', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Biotechnology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Plant Biotechnology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Animal Biotechnology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Microbial Biotechnology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Industrial Biotechnology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Environmental Biotechnology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Marine Biotechnology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Molecular Biotechnology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Genomics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Proteomics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Metabolomics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Transcriptomics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Phenomics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Bioinformatics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Computational Biology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Informatics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Biostatistics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Statistics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Experimental Design', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Sampling Theory', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Modelling', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Simulation Modelling', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Systems Analysis', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Operations Research', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Decision Science', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Geography', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural History', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Anthropology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Philosophy', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Ethics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Law', 'Agriculture, Forestry & Natural Resources', 'Undergraduate')
,
('BA Sociology', 'Social Sciences', 'Undergraduate'),
('BA Social Work', 'Social Sciences', 'Undergraduate'),
('BA Psychology', 'Social Sciences', 'Undergraduate'),
('BA Political Science', 'Social Sciences', 'Undergraduate'),
('BA International Relations', 'Social Sciences', 'Undergraduate'),
('BA Public Administration', 'Social Sciences', 'Undergraduate'),
('BA Geography', 'Social Sciences', 'Undergraduate'),
('BA History', 'Social Sciences', 'Undergraduate'),
('BA Archaeology', 'Social Sciences', 'Undergraduate'),
('BA Anthropology', 'Social Sciences', 'Undergraduate'),
('BA Philosophy', 'Social Sciences', 'Undergraduate'),
('BA Religious Studies', 'Social Sciences', 'Undergraduate'),
('BA Theology', 'Social Sciences', 'Undergraduate'),
('BA Christian Ministry', 'Social Sciences', 'Undergraduate'),
('BA Islamic Studies', 'Social Sciences', 'Undergraduate'),
('BA African Studies', 'Social Sciences', 'Undergraduate'),
('BA Development Studies', 'Social Sciences', 'Undergraduate'),
('BA Gender Studies', 'Social Sciences', 'Undergraduate'),
('BA Peace Studies', 'Social Sciences', 'Undergraduate'),
('BA Conflict Resolution', 'Social Sciences', 'Undergraduate'),
('BA Security Studies', 'Social Sciences', 'Undergraduate'),
('BA Defence and Strategic Studies', 'Social Sciences', 'Undergraduate'),
('BA Governance', 'Social Sciences', 'Undergraduate'),
('BA Local Government Administration', 'Social Sciences', 'Undergraduate'),
('BA Public Policy', 'Social Sciences', 'Undergraduate'),
('BA Social Policy', 'Social Sciences', 'Undergraduate'),
('BA Environmental Policy', 'Social Sciences', 'Undergraduate'),
('BA Labour Studies', 'Social Sciences', 'Undergraduate'),
('BA Industrial Relations', 'Social Sciences', 'Undergraduate'),
('BA Population Studies', 'Social Sciences', 'Undergraduate'),
('BA Demography', 'Social Sciences', 'Undergraduate'),
('BA Migration Studies', 'Social Sciences', 'Undergraduate'),
('BA Refugee Studies', 'Social Sciences', 'Undergraduate'),
('BA Disability Studies', 'Social Sciences', 'Undergraduate'),
('BA Gerontology', 'Social Sciences', 'Undergraduate'),
('BA Youth Studies', 'Social Sciences', 'Undergraduate'),
('BA Child Studies', 'Social Sciences', 'Undergraduate'),
('BA Family Studies', 'Social Sciences', 'Undergraduate'),
('BA Community Development', 'Social Sciences', 'Undergraduate'),
('BA Rural Development', 'Social Sciences', 'Undergraduate'),
('BA Urban Development', 'Social Sciences', 'Undergraduate'),
('BA Regional Development', 'Social Sciences', 'Undergraduate'),
('BA National Development', 'Social Sciences', 'Undergraduate'),
('BA International Development', 'Social Sciences', 'Undergraduate'),
('BA Sustainable Development', 'Social Sciences', 'Undergraduate'),
('BA Human Development', 'Social Sciences', 'Undergraduate'),
('BA Social Development', 'Social Sciences', 'Undergraduate'),
('BA Economic Development', 'Social Sciences', 'Undergraduate'),
('BA Cultural Development', 'Social Sciences', 'Undergraduate'),
('BA Political Development', 'Social Sciences', 'Undergraduate'),
('BA Institutional Development', 'Social Sciences', 'Undergraduate'),
('BA Organizational Development', 'Social Sciences', 'Undergraduate'),
('BA Community Organizing', 'Social Sciences', 'Undergraduate'),
('BA Social Movements', 'Social Sciences', 'Undergraduate'),
('BA Civic Engagement', 'Social Sciences', 'Undergraduate'),
('BA Volunteer Management', 'Social Sciences', 'Undergraduate'),
('BA Nonprofit Management', 'Social Sciences', 'Undergraduate'),
('BA NGO Management', 'Social Sciences', 'Undergraduate'),
('BA Civil Society Studies', 'Social Sciences', 'Undergraduate'),
('BA Social Entrepreneurship', 'Social Sciences', 'Undergraduate'),
('BA Social Innovation', 'Social Sciences', 'Undergraduate'),
('BA Social Enterprise', 'Social Sciences', 'Undergraduate'),
('BA Social Finance', 'Social Sciences', 'Undergraduate'),
('BA Social Investment', 'Social Sciences', 'Undergraduate'),
('BA Impact Investment', 'Social Sciences', 'Undergraduate'),
('BA Social Impact Assessment', 'Social Sciences', 'Undergraduate'),
('BA Social Return on Investment', 'Social Sciences', 'Undergraduate'),
('BA Social Accounting', 'Social Sciences', 'Undergraduate'),
('BA Social Auditing', 'Social Sciences', 'Undergraduate'),
('BA Social Reporting', 'Social Sciences', 'Undergraduate'),
('BA Social Performance Management', 'Social Sciences', 'Undergraduate'),
('BA Social Measurement', 'Social Sciences', 'Undergraduate'),
('BA Social Statistics', 'Social Sciences', 'Undergraduate'),
('BA Social Research Methods', 'Social Sciences', 'Undergraduate'),
('BA Qualitative Research', 'Social Sciences', 'Undergraduate'),
('BA Quantitative Research', 'Social Sciences', 'Undergraduate'),
('BA Mixed Methods Research', 'Social Sciences', 'Undergraduate'),
('BA Participatory Research', 'Social Sciences', 'Undergraduate'),
('BA Action Research', 'Social Sciences', 'Undergraduate'),
('BA Community-Based Research', 'Social Sciences', 'Undergraduate'),
('BA Transdisciplinary Research', 'Social Sciences', 'Undergraduate'),
('BA Interdisciplinary Research', 'Social Sciences', 'Undergraduate'),
('BA Multidisciplinary Research', 'Social Sciences', 'Undergraduate'),
('BA Cross-Cultural Research', 'Social Sciences', 'Undergraduate'),
('BA Comparative Research', 'Social Sciences', 'Undergraduate'),
('BA Longitudinal Research', 'Social Sciences', 'Undergraduate'),
('BA Experimental Research', 'Social Sciences', 'Undergraduate'),
('BA Quasi-Experimental Research', 'Social Sciences', 'Undergraduate'),
('BA Survey Research', 'Social Sciences', 'Undergraduate'),
('BA Case Study Research', 'Social Sciences', 'Undergraduate'),
('BA Ethnographic Research', 'Social Sciences', 'Undergraduate'),
('BA Phenomenological Research', 'Social Sciences', 'Undergraduate'),
('BA Grounded Theory Research', 'Social Sciences', 'Undergraduate'),
('BA Narrative Research', 'Social Sciences', 'Undergraduate'),
('BA Discourse Analysis', 'Social Sciences', 'Undergraduate'),
('BA Content Analysis', 'Social Sciences', 'Undergraduate'),
('BA Textual Analysis', 'Social Sciences', 'Undergraduate'),
('BA Visual Analysis', 'Social Sciences', 'Undergraduate'),
('BA Spatial Analysis', 'Social Sciences', 'Undergraduate'),
('BA Temporal Analysis', 'Social Sciences', 'Undergraduate'),
('BA Network Analysis', 'Social Sciences', 'Undergraduate'),
('BA Social Network Analysis', 'Social Sciences', 'Undergraduate'),
('BA Computational Social Science', 'Social Sciences', 'Undergraduate'),
('BA Digital Social Science', 'Social Sciences', 'Undergraduate'),
('BA Data Science for Social Sciences', 'Social Sciences', 'Undergraduate'),
('BA Artificial Intelligence for Social Sciences', 'Social Sciences', 'Undergraduate'),
('BA Machine Learning for Social Sciences', 'Social Sciences', 'Undergraduate'),
('BA Big Data Analytics for Social Sciences', 'Social Sciences', 'Undergraduate'),
('BA Social Media Analytics', 'Social Sciences', 'Undergraduate'),
('BA Sentiment Analysis', 'Social Sciences', 'Undergraduate'),
('BA Opinion Mining', 'Social Sciences', 'Undergraduate'),
('BA Text Mining', 'Social Sciences', 'Undergraduate'),
('BA Web Mining', 'Social Sciences', 'Undergraduate'),
('BA Data Mining', 'Social Sciences', 'Undergraduate'),
('BA Knowledge Discovery', 'Social Sciences', 'Undergraduate'),
('BA Information Retrieval', 'Social Sciences', 'Undergraduate'),
('BA Information Science', 'Social Sciences', 'Undergraduate'),
('BA Library Science', 'Social Sciences', 'Undergraduate'),
('BA Archival Science', 'Social Sciences', 'Undergraduate'),
('BA Records Management', 'Social Sciences', 'Undergraduate'),
('BA Knowledge Management', 'Social Sciences', 'Undergraduate'),
('BA Information Management', 'Social Sciences', 'Undergraduate'),
('BA Data Management', 'Social Sciences', 'Undergraduate'),
('BA Document Management', 'Social Sciences', 'Undergraduate'),
('BA Content Management', 'Social Sciences', 'Undergraduate'),
('BA Digital Asset Management', 'Social Sciences', 'Undergraduate'),
('BA Enterprise Content Management', 'Social Sciences', 'Undergraduate'),
('BA Web Content Management', 'Social Sciences', 'Undergraduate'),
('BA Social Content Management', 'Social Sciences', 'Undergraduate'),
('BA Media Content Management', 'Social Sciences', 'Undergraduate'),
('BA News Content Management', 'Social Sciences', 'Undergraduate'),
('BA Entertainment Content Management', 'Social Sciences', 'Undergraduate'),
('BA Educational Content Management', 'Social Sciences', 'Undergraduate'),
('BA Scientific Content Management', 'Social Sciences', 'Undergraduate'),
('BA Technical Content Management', 'Social Sciences', 'Undergraduate'),
('BA Legal Content Management', 'Social Sciences', 'Undergraduate'),
('BA Medical Content Management', 'Social Sciences', 'Undergraduate'),
('BA Financial Content Management', 'Social Sciences', 'Undergraduate'),
('BA Marketing Content Management', 'Social Sciences', 'Undergraduate'),
('BA Advertising Content Management', 'Social Sciences', 'Undergraduate'),
('BA Public Relations Content Management', 'Social Sciences', 'Undergraduate'),
('BA Corporate Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Internal Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA External Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Crisis Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Risk Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Health Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Science Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Environmental Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Development Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Agricultural Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Rural Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Urban Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Community Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Intercultural Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA International Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Cross-Border Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Transnational Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Global Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Local Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA National Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Regional Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Continental Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Diaspora Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Indigenous Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Traditional Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Folk Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Popular Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Mass Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Broadcast Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Print Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Digital Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Mobile Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Wireless Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Satellite Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Fibre Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Cable Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Microwave Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Radio Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Television Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Cinema Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Theatre Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Performance Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Music Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Dance Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Visual Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Fine Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Applied Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Decorative Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Graphic Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Plastic Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Performing Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Literary Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Culinary Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Martial Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Healing Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Spiritual Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Sacred Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Ritual Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Festival Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Carnival Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Street Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Public Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Community Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Participatory Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Collaborative Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Socially Engaged Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Activist Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Protest Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Resistance Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Liberation Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Decolonial Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Postcolonial Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Anti-Colonial Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Pan-African Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Afrocentric Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Afrofuturist Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Afro-Surrealist Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Negritude Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Consciousness Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Power Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Arts Movement Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Harlem Renaissance Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Chicago Black Renaissance Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Mountain Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Atlantic Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Pacific Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Mediterranean Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Indian Ocean Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Arctic Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Antarctic Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Cosmic Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Planetary Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Galactic Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Universal Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Eternal Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Infinite Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Absolute Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Ultimate Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Supreme Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Divine Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Sacred Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Holy Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Blessed Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Consecrated Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Hallowed Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Sanctified Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Ordained Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Anointed Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Chosen Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Elect Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Predestined Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Foreordained Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Predetermined Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Fated Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Destined Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Doom Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Karma Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Dharma Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Tao Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Zen Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Yoga Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Meditation Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Mindfulness Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Contemplation Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Reflection Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Introspection Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Self-Examination Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Self-Knowledge Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Self-Awareness Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Self-Realization Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Self-Actualization Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Self-Transcendence Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Self-Transformation Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Self-Evolution Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Self-Development Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Self-Improvement Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Self-Enhancement Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Self-Enrichment Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Self-Empowerment Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Self-Liberation Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Self-Determination Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Self-Governance Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Self-Rule Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Self-Government Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Self-Administration Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Self-Management Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Self-Organization Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Self-Coordination Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Self-Regulation Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Self-Control Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Self-Discipline Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Self-Restraint Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Self-Denial Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Self-Sacrifice Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Selflessness Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Altruism Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Philanthropy Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Charity Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Benevolence Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Compassion Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Empathy Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Sympathy Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Kindness Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Generosity Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Hospitality Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Welcome Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Inclusion Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Belonging Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Acceptance Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Tolerance Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Respect Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Dignity Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Honour Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Integrity Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Honesty Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Truth Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Justice Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Fairness Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Equity Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Equality Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Freedom Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Liberty Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Rights Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Democracy Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Republic Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Nation Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black State Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Country Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Homeland Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Motherland Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Fatherland Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Ancestral Land Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Native Land Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Indigenous Land Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Traditional Land Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Customary Land Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Communal Land Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Collective Land Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Cooperative Land Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Shared Land Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Common Land Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Public Land Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Government Land Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black State Land Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Crown Land Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Trust Land Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Leasehold Land Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Freehold Land Arts Communication Content Management', 'Social Sciences', 'Undergraduate'),
('BA Black Allodial Land Arts Communication Content Management', 'Social Sciences', 'Undergraduate')
ON CONFLICT (name) DO NOTHING;

COMMIT;
