-- Migration: Seed all Ghanaian institutions (replace existing data)
-- This script clears the existing institutions table and inserts the provided list.

-- Delete existing rows
DELETE FROM public.institutions;

-- Insert new institutions
INSERT INTO public.institutions (name, abbreviation, domain, country, city, type, verified)
SELECT * FROM (VALUES
  -- Private Universities
  ('Academic City University', 'ACity', 'acity.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Accra Metropolitan University', 'AMU', 'accrametrouni.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('African University of Communication and Business', 'AUCB', 'aucb.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Akrofi-Christaller Institute of Theology, Mission and Culture', 'ACI', 'aci.edu.gh', 'Ghana', 'Akropong', 'Private University', TRUE),
  ('All Nations University', 'ANU', 'anu.edu.gh', 'Ghana', 'Koforidua', 'Private University', TRUE),
  ('Ashesi University', 'Ashesi', 'ashesi.edu.gh', 'Ghana', 'Berekuso', 'Private University', TRUE),
  ('Catholic University College of Ghana', 'CUG', 'cug.edu.gh', 'Ghana', 'Sunyani', 'Private University', TRUE),
  ('Central University', 'CU', 'central.edu.gh', 'Ghana', 'Accra / Tema', 'Private University', TRUE),
  ('Christian Service University', 'CSUC', 'csuc.edu.gh', 'Ghana', 'Kumasi', 'Private University', TRUE),
  ('Ensign Global University', 'EGU', 'ensign.edu.gh', 'Ghana', 'Kpong', 'Private University', TRUE),
  ('Entrance University of Health Sciences', 'EUHS', 'entrance.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Family Health University', 'FHU', 'familyhealthuniversity.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Garden City University', 'GCU', 'gcuc.edu.gh', 'Ghana', 'Kumasi', 'Private University', TRUE),
  ('Heritage Christian University', 'HCU', 'hcu.edu.gh', 'Ghana', 'Amasaman', 'Private University', TRUE),
  ('KAAF University', 'KAAF', 'kaaf.edu.gh', 'Ghana', 'Gomoa Fetteh', 'Private University', TRUE),
  ('Knutsford University', 'Knutsford', 'knutsford.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Methodist University Ghana', 'MUCG', 'methodist.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('NiBS University', 'NiBS', 'nibs.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Pentecost University', 'PU', 'pentvars.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Presbyterian University', 'PUC', 'presbyuniversity.edu.gh', 'Ghana', 'Abetifi', 'Private University', TRUE),
  ('Thrivus University for Biomedical Science and Technology', 'Thrivus', 'thrivus.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Trinity Theological Seminary', 'TTS', 'tts.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('University of Gold Coast', 'UGC', 'ugc.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Valley View University', 'VVU', 'vvu.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  -- Foreign Affiliated
  ('Business University of Costa Rica', 'UNEM', 'unem.edu', 'Ghana', 'Kumasi', 'Foreign Affiliated', TRUE),
  ('Lancaster University Ghana', 'LUG', 'lancaster.edu.gh', 'Ghana', 'Accra', 'Foreign Affiliated', TRUE),
  ('Malaysia University of Science and Technology Ghana Campus', 'MUST', 'must.edu.my', 'Ghana', 'Accra', 'Foreign Affiliated', TRUE),
  ('Open University of Malaysia Ghana Campus', 'OUM', 'oum.edu.my', 'Ghana', 'Accra', 'Foreign Affiliated', TRUE),
  ('Webster University Ghana', 'Webster', 'webster.edu.gh', 'Ghana', 'Accra', 'Foreign Affiliated', TRUE),
  -- Private University (additional)
  ('Accra Institute of Technology', 'AIT', 'ait.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Advance Global University College', 'AGUC', 'advanceglobal.edu.gh', 'Ghana', 'Tamale', 'Private University', TRUE),
  ('African Institute for Mathematical Sciences Ghana', 'AIMS Ghana', 'aims.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('African University College of Communications', 'AUCC', 'aucc.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Akim State College', 'ASC', 'akimstate.edu.gh', 'Ghana', 'Akim Oda', 'Private University', TRUE),
  ('Amen College of Health Sciences', 'ACHS', 'amencollege.edu.gh', 'Ghana', 'Kumasi', 'Private University', TRUE),
  ('Anglican University College of Technology', 'AUCT', 'anglicanuc.edu.gh', 'Ghana', 'Nkoranza', 'Private University', TRUE),
  ('Apex University College', 'Apex', 'apexuniversity.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Apostolic Church Theological Seminary', 'ACTS', 'acts.edu.gh', 'Ghana', 'Kumasi', 'Private University', TRUE),
  ('Baldwin College', 'Baldwin', 'baldwincollege.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('BlueCrest College', 'BlueCrest', 'bluecrest.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Bunso Cocoa College', 'BCC', 'bunsococoa.edu.gh', 'Ghana', 'Bunso', 'Private University', TRUE),
  ('CSIR College of Science and Technology', 'CSIR-CST', 'csircst.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Carest College of Health', 'Carest', 'carest.edu.gh', 'Ghana', 'Hohoe', 'Private University', TRUE),
  ('Central College of Science and Technology', 'CCST', 'centralcollege.edu.gh', 'Ghana', 'Agona Swedru', 'Private University', TRUE),
  ('China Europe International Business School Africa Campus', 'CEIBS', 'ceibs.edu/gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Christ Apostolic University College', 'CAUC', 'cauc.edu.gh', 'Ghana', 'Kumasi', 'Private University', TRUE),
  ('College of Islamic Studies', 'CIS', 'cis.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('College of Medicine and Allied Sciences', 'COMAS', 'comas.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('DHI College of Health and Education', 'DHI', 'dhicollege.edu.gh', 'Ghana', 'Kumasi', 'Private University', TRUE),
  ('Data Link Institute of Business and Technology', 'DLIBT', 'datalink.edu.gh', 'Ghana', 'Tema', 'Private University', TRUE),
  ('Delexes University College', 'Delexes', 'delexes.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Duffuor University College', 'DUC', 'duffuoruniversity.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Entrepreneurship Training Institute', 'ETI', 'eti.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Evangelical Presbyterian University College', 'EPUC', 'epuc.edu.gh', 'Ghana', 'Ho', 'Private University', TRUE),
  ('Fanaka International University College', 'Fanaka', 'fanakauc.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Flosam Institute of Nursing and Allied Health Sciences', 'Flosam', 'flosam.edu.gh', 'Ghana', 'Suhum', 'Private University', TRUE),
  ('Fountainhead Christian University College', 'FCUC', 'fountainhead.edu.gh', 'Ghana', 'Tema', 'Private University', TRUE),
  ('GNAT Institute for Research and Industrial Relations Studies', 'GNAT-IRIRS', 'gnatirrs.edu.gh', 'Ghana', 'Ejisu', 'Private University', TRUE),
  ('Ghana Baptist University College', 'GBUC', 'gbuc.edu.gh', 'Ghana', 'Kumasi', 'Private University', TRUE),
  ('Ghana Christian University College', 'GCUC', 'ghanacu.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Ghana Insurance College', 'GIC', 'gic.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Global Theological Seminary', 'GTS', 'globaltheological.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Good News Theological Seminary', 'GNTS', 'goodnews.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('High Skies College', 'HSC', 'highskies.edu.gh', 'Ghana', 'Tema', 'Private University', TRUE),
  ('Holy Eucharist University College', 'HEUC', 'holyeucharist.edu.gh', 'Ghana', 'Half Assini', 'Private University', TRUE),
  ('Institute for Security, Disaster and Emergency Studies', 'ISDES', 'isdes.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Institute of Development and Technology Management', 'IDTM', 'idtm.edu.gh', 'Ghana', 'Cape Coast', 'Private University', TRUE),
  ('Islamic University College', 'IUCG', 'iucg.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('JACCD Design Institute Africa', 'JACCD', 'jaccd.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Jackson University College', 'Jackson', 'jacksonuniversity.edu.gh', 'Ghana', 'Kumasi', 'Private University', TRUE),
  ('Jayee University College', 'Jayee', 'jayeeuniversity.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Justking College', 'Justking', 'justking.edu.gh', 'Ghana', 'Sefwi', 'Private University', TRUE),
  ('Kessben University College', 'Kessben', 'kessbenuniversity.edu.gh', 'Ghana', 'Kumasi', 'Private University', TRUE),
  ('Kings University College', 'KUC', 'kingsuniversity.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Klintaps College of Health and Allied Sciences', 'Klintaps', 'klintaps.edu.gh', 'Ghana', 'Tema', 'Private University', TRUE),
  ('Maranatha University College', 'Maranatha', 'maranatha.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Medicare College of Applied Sciences', 'MCAS', 'medicarecollege.edu.gh', 'Ghana', 'Kumasi', 'Private University', TRUE),
  ('Miezah University College', 'Miezah', 'miezahuniversity.edu.gh', 'Ghana', 'Kumasi', 'Private University', TRUE),
  ('Millar Institute of Transdisciplinary And Development Studies', 'Millar', 'millar.edu.gh', 'Ghana', 'Bolgatanga', 'Private University', TRUE),
  ('Mountcrest University College', 'Mountcrest', 'mountcrest.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('National Defence University', 'NDU', 'ndu.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Nduom School of Business and Technology', 'NSBT', 'nsbt.edu.gh', 'Ghana', 'Elmina', 'Private University', TRUE),
  ('Neumann College', 'Neumann', 'neumanncollege.edu.gh', 'Ghana', 'Kumasi', 'Private University', TRUE),
  ('New Life College', 'NLC', 'newlifecollege.edu.gh', 'Ghana', 'Tamale', 'Private University', TRUE),
  ('Nyansapo College', 'Nyansapo', 'nyansapo.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('OTE School of Journalism and Communication Studies', 'OTE', 'oteschool.edu.gh', 'Ghana', 'Kumasi', 'Private University', TRUE),
  ('Oheneba-Dornyo University College of Counselling Psychology', 'ODUCCP', 'oduccp.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Organization Development Institute', 'ODI', 'odi.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Palm University College', 'Palm', 'palmuniversity.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Perez University College', 'Perez', 'perezuniversity.edu.gh', 'Ghana', 'Winneba', 'Private University', TRUE),
  ('Pharmatrust Professional College', 'Pharmatrust', 'pharmatrust.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Radford University College', 'Radford', 'radford.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Redeemer College of Health', 'RCH', 'redeemercollege.edu.gh', 'Ghana', 'Tarkwa', 'Private University', TRUE),
  ('Regent University College of Science and Technology', 'Regent', 'regent.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Regentropfen University College', 'Regentropfen', 'regentropfen.edu.gh', 'Ghana', 'Bongo', 'Private University', TRUE),
  ('Rosebank International University College', 'Rosebank', 'rosebank.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('SALT University College', 'SALT', 'saltuniversity.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('SIIMT University College', 'SIIMT', 'siimt.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Southshore University College', 'Southshore', 'southshore.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Spiritan University College', 'SUC', 'spiritan.edu.gh', 'Ghana', 'Ejisu', 'Private University', TRUE),
  ('St. Mary''s College of Health Science', 'SMCHS', 'stmaryshealth.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Techbridge University College', 'Techbridge', 'techbridge.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('University College of Agriculture and Environmental Studies', 'UCAES', 'ucaes.edu.gh', 'Ghana', 'Bunso', 'Private University', TRUE),
  ('University College of Management Studies', 'UCOMS', 'ucoms.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('West End University College', 'West End', 'westenduniversity.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Wisconsin International University College', 'WIUC', 'wiuc-ghana.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  ('Zenith University College', 'ZUC', 'zenithuniversity.edu.gh', 'Ghana', 'Accra', 'Private University', TRUE),
  -- Public Professional
  ('Ghana Armed Forces Command and Staff College', 'GAFCSC', 'gafcsc.mil.gh', 'Ghana', 'Accra', 'Public Professional', TRUE),
  ('Ghana Institute of Journalism', 'GIJ', 'gij.edu.gh', 'Ghana', 'Accra', 'Public Professional', TRUE),
  ('Ghana Institute of Languages', 'GIL', 'gil.edu.gh', 'Ghana', 'Accra', 'Public Professional', TRUE),
  ('Ghana Institute of Surveying and Mapping', 'GISM', 'gism.edu.gh', 'Ghana', 'Accra', 'Public Professional', TRUE),
  ('Institute of Local Government Studies', 'ILGS', 'ilgs.edu.gh', 'Ghana', 'Accra', 'Public Professional', TRUE),
  ('Kofi Annan International Peacekeeping Training Centre', 'KAIPTC', 'kaiptc.org', 'Ghana', 'Accra', 'Public Professional', TRUE),
  ('National Film and Television Institute', 'NAFTI', 'nafti.edu.gh', 'Ghana', 'Accra', 'Public Professional', TRUE),
  ('Regional Maritime University', 'RMU', 'rmu.edu.gh', 'Ghana', 'Accra', 'Public Professional', TRUE),
  -- Technical Universities
  ('Accra Technical University', 'ATU', 'atu.edu.gh', 'Ghana', 'Accra', 'Technical University', TRUE),
  ('Bolgatanga Technical University', 'BTU', 'btu.edu.gh', 'Ghana', 'Bolgatanga', 'Technical University', TRUE),
  ('Cape Coast Technical University', 'CCTU', 'cctu.edu.gh', 'Ghana', 'Cape Coast', 'Technical University', TRUE),
  ('Dr. Hilla Limann Technical University', 'DHL-TU', 'dhl-tu.edu.gh', 'Ghana', 'Wa', 'Technical University', TRUE),
  ('Ho Technical University', 'HTU', 'htu.edu.gh', 'Ghana', 'Ho', 'Technical University', TRUE),
  ('Koforidua Technical University', 'KTU', 'ktu.edu.gh', 'Ghana', 'Koforidua', 'Technical University', TRUE),
  ('Kumasi Technical University', 'KsTU', 'kstu.edu.gh', 'Ghana', 'Kumasi', 'Technical University', TRUE),
  ('Sunyani Technical University', 'STU', 'stu.edu.gh', 'Ghana', 'Sunyani', 'Technical University', TRUE),
  ('Takoradi Technical University', 'TTU', 'ttu.edu.gh', 'Ghana', 'Takoradi', 'Technical University', TRUE),
  ('Tamale Technical University', 'TATU', 'tatu.edu.gh', 'Ghana', 'Tamale', 'Technical University', TRUE),
  -- Public Universities
  ('Akenten Appiah-Menka University of Skills Training and Entrepreneurial Development', 'AAM-USTED', 'aamusted.edu.gh', 'Ghana', 'Kumasi', 'Public University', TRUE),
  ('C.K. Tedam University of Technology and Applied Sciences', 'CKT-UTAS', 'cktutas.edu.gh', 'Ghana', 'Navrongo', 'Public University', TRUE),
  ('Ghana Communication Technology University', 'GCTU', 'gctu.edu.gh', 'Ghana', 'Accra', 'Public University', TRUE),
  ('Ghana Institute of Management and Public Administration', 'GIMPA', 'gimpa.edu.gh', 'Ghana', 'Accra', 'Public University', TRUE),
  ('Kwame Nkrumah University of Science and Technology', 'KNUST', 'knust.edu.gh', 'Ghana', 'Kumasi', 'Public University', TRUE),
  ('Simon Diedong Dombo University of Business and Integrated Development Studies', 'SDD-UBIDS', 'ubids.edu.gh', 'Ghana', 'Wa', 'Public University', TRUE),
  ('University for Development Studies', 'UDS', 'uds.edu.gh', 'Ghana', 'Tamale', 'Public University', TRUE),
  ('University of Cape Coast', 'UCC', 'ucc.edu.gh', 'Ghana', 'Cape Coast', 'Public University', TRUE),
  ('University of Education, Winneba', 'UEW', 'uew.edu.gh', 'Ghana', 'Winneba', 'Public University', TRUE),
  ('University of Energy and Natural Resources', 'UENR', 'uenr.edu.gh', 'Ghana', 'Sunyani', 'Public University', TRUE),
  ('University of Environment and Sustainable Development', 'UESD', 'uesd.edu.gh', 'Ghana', 'Somanya', 'Public University', TRUE),
  ('University of Ghana', 'UG', 'ug.edu.gh', 'Ghana', 'Legon, Accra', 'Public University', TRUE),
  ('University of Health and Allied Sciences', 'UHAS', 'uhas.edu.gh', 'Ghana', 'Ho', 'Public University', TRUE),
  ('University of Media, Arts and Communication', 'UniMAC', 'unimac.edu.gh', 'Ghana', 'Accra', 'Public University', TRUE),
  ('University of Mines and Technology', 'UMaT', 'umat.edu.gh', 'Ghana', 'Tarkwa', 'Public University', TRUE),
  ('University of Professional Studies, Accra', 'UPSA', 'upsa.edu.gh', 'Ghana', 'Accra', 'Public University', TRUE)
) AS v(name, abbreviation, domain, country, city, type, verified);

-- Enable RLS if required (keeping existing policies)
-- ALTER TABLE public.institutions ENABLE ROW LEVEL SECURITY;
