-- Migration: Insert missing programmes (Batches 5, 9, 6)
BEGIN;

-- Add unique constraint if not exists (Postgres 11+ syntax or standard constraint)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'course_programmes_name_key') THEN
        -- Remove duplicates before adding the unique constraint
        DELETE FROM public.course_programmes a USING public.course_programmes b WHERE a.ctid < b.ctid AND a.name = b.name;
        
        ALTER TABLE public.course_programmes ADD CONSTRAINT course_programmes_name_key UNIQUE (name);
    END IF;
END $$;

INSERT INTO public.course_programmes (name, field, level) VALUES
('BSc Business Administration', 'Business, Management & Administration', 'Undergraduate'),
('BSc Accounting', 'Business, Management & Administration', 'Undergraduate'),
('BSc Banking and Finance', 'Business, Management & Administration', 'Undergraduate'),
('BSc Marketing', 'Business, Management & Administration', 'Undergraduate'),
('BSc Human Resource Management', 'Business, Management & Administration', 'Undergraduate'),
('BSc International Business', 'Business, Management & Administration', 'Undergraduate'),
('BSc Logistics and Supply Chain Management', 'Business, Management & Administration', 'Undergraduate'),
('BSc Entrepreneurship', 'Business, Management & Administration', 'Undergraduate'),
('BSc Procurement and Supply Chain Management', 'Business, Management & Administration', 'Undergraduate'),
('BSc Operations Management', 'Business, Management & Administration', 'Undergraduate'),
('BSc Risk Management and Insurance', 'Business, Management & Administration', 'Undergraduate'),
('BSc Actuarial Science', 'Business, Management & Administration', 'Undergraduate'),
('BSc Economics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Statistics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Mathematics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Financial Economics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Agribusiness Management', 'Business, Management & Administration', 'Undergraduate'),
('BSc Hospitality and Tourism Management', 'Business, Management & Administration', 'Undergraduate'),
('BSc Event Management', 'Business, Management & Administration', 'Undergraduate'),
('BSc Real Estate Management', 'Business, Management & Administration', 'Undergraduate'),
('BSc Project Management', 'Business, Management & Administration', 'Undergraduate'),
('BSc Business Information Systems', 'Business, Management & Administration', 'Undergraduate'),
('BSc E-Commerce', 'Business, Management & Administration', 'Undergraduate'),
('BSc Digital Marketing', 'Business, Management & Administration', 'Undergraduate'),
('BSc Brand Management', 'Business, Management & Administration', 'Undergraduate'),
('BSc Customer Relationship Management', 'Business, Management & Administration', 'Undergraduate'),
('BSc Retail Management', 'Business, Management & Administration', 'Undergraduate'),
('BSc Sales Management', 'Business, Management & Administration', 'Undergraduate'),
('BSc Export and Import Management', 'Business, Management & Administration', 'Undergraduate'),
('BSc Trade and Investment', 'Business, Management & Administration', 'Undergraduate'),
('BSc Development Economics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Environmental Economics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Agricultural Economics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Resource Economics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Health Economics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Labour Economics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Transport Economics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Urban Economics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Demography', 'Business, Management & Administration', 'Undergraduate'),
('BSc Econometrics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Applied Statistics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Biostatistics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Financial Mathematics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Industrial Mathematics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Computational Mathematics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Applied Mathematics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Pure Mathematics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Mathematical Biology', 'Business, Management & Administration', 'Undergraduate'),
('BSc Mathematical Physics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Mathematical Economics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Mathematical Finance', 'Business, Management & Administration', 'Undergraduate'),
('BSc Mathematical Statistics', 'Business, Management & Administration', 'Undergraduate'),
('BSc Agriculture', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Science', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Animal Science', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Animal Production', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Animal Health', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Animal Nutrition', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Animal Breeding and Genetics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Animal Physiology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Animal Behaviour', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Animal Welfare', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Animal Husbandry', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Livestock Production', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Poultry Science', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Aquaculture', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Fisheries Science', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Fish Science', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Marine Fisheries', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Inland Fisheries', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Fish Processing Technology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Crop Science', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Crop Production', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Crop Protection', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Crop Physiology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Crop Breeding', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Crop Genetics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Crop Biotechnology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Crop Ecology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Crop Pathology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Crop Entomology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Crop Nematology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Crop Virology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Crop Mycology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Crop Bacteriology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Horticulture', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Ornamental Horticulture', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Landscape Horticulture', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Olericulture', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Pomology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Floriculture', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Viticulture', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Post-Harvest Technology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Soil Science', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Soil Chemistry', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Soil Physics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Soil Biology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Soil Microbiology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Soil Fertility', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Soil Conservation', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Soil Survey', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Soil Classification', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Soil Genesis', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Soil Mineralogy', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Soil Pedology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Soil Edaphology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agronomy', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Weed Science', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Plant Pathology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Plant Virology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Plant Nematology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Plant Entomology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Plant Mycology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Plant Bacteriology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Extension', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Rural Development', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Communication', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Education', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Engineering', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Mechanization', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Farm Machinery', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Irrigation Technology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Drainage Engineering', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Water Management', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Meteorology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Climatology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Biotechnology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Genetics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Microbiology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Biochemistry', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Economics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Policy', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Finance', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Marketing', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Trade', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Cooperatives', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Statistics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Informatics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Precision Agriculture', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Smart Agriculture', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Digital Agriculture', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Climate-Smart Agriculture', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Conservation Agriculture', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Sustainable Agriculture', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Organic Agriculture', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agroecology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agroforestry', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Silviculture', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Forest Management', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Forest Ecology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Forest Conservation', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Forest Genetics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Forest Pathology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Forest Entomology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Forest Products', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Wood Science', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Wood Technology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Timber Engineering', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Pulp and Paper Technology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Forest Policy', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Forest Economics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Wildlife Management', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Wildlife Ecology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Wildlife Conservation', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Wildlife Biology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Wildlife Health', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Wildlife Veterinary Science', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Range Management', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Pasture Science', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Grassland Science', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Rangeland Ecology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Natural Resource Management', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Environmental Resource Management', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Water Resource Management', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Land Resource Management', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Coastal Resource Management', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Marine Resource Management', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Biodiversity Conservation', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Ecosystem Management', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Wetland Management', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Mangrove Management', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Watershed Management', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Catchment Management', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Land Use Planning', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Rural Planning', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Community Development', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Rural Sociology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Sociology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Food Science', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Food Technology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Food Processing', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Food Engineering', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Food Microbiology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Food Chemistry', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Food Biochemistry', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Food Nutrition', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Food Safety', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Food Quality Assurance', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Food Packaging', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Food Preservation', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Food Product Development', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Food Sensory Science', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Food Rheology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Food Toxicology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Nutrition Science', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Human Nutrition', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Community Nutrition', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Clinical Nutrition', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Public Health Nutrition', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Sports Nutrition', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Animal Nutrition', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Pet Nutrition', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Aquatic Nutrition', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Biotechnology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Plant Biotechnology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Animal Biotechnology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Microbial Biotechnology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Industrial Biotechnology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Environmental Biotechnology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Marine Biotechnology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Molecular Biotechnology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Genomics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Proteomics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Metabolomics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Transcriptomics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Phenomics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Bioinformatics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Computational Biology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Informatics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Biostatistics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Statistics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Experimental Design', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Sampling Theory', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Modelling', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Simulation Modelling', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Systems Analysis', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Operations Research', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Decision Science', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Geography', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural History', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Anthropology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Philosophy', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Ethics', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Law', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Policy', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Governance', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Administration', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Leadership', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Entrepreneurship', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Innovation', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Technology Transfer', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Knowledge Management', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Communication Technology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Media', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Journalism', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Public Relations', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Advocacy', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Diplomacy', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Negotiation', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Conflict Resolution', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Peacebuilding', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Security', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Risk Management', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Insurance', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Finance', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Investment', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Banking', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Credit', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Microfinance', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Development', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Project Management', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Programme Evaluation', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Impact Assessment', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Monitoring and Evaluation', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Gender Studies', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Youth Studies', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Indigenous Knowledge', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Traditional Knowledge', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Cultural Heritage', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Archaeology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('BSc Agricultural Palaeontology', 'Agriculture, Forestry & Natural Resources', 'Undergraduate'),
('MBA', 'Business, Management & Administration', 'Postgraduate'),
('EMBA Executive Master of Business Administration', 'Business, Management & Administration', 'Postgraduate'),
('MSc Finance', 'Business, Management & Administration', 'Postgraduate'),
('MSc Accounting', 'Business, Management & Administration', 'Postgraduate'),
('MSc Marketing', 'Business, Management & Administration', 'Postgraduate'),
('MSc Human Resource Management', 'Business, Management & Administration', 'Postgraduate'),
('MSc International Business', 'Business, Management & Administration', 'Postgraduate'),
('MSc Entrepreneurship', 'Business, Management & Administration', 'Postgraduate'),
('MSc Supply Chain Management', 'Business, Management & Administration', 'Postgraduate'),
('MSc Project Management', 'Business, Management & Administration', 'Postgraduate'),
('MSc Development Finance', 'Business, Management & Administration', 'Postgraduate'),
('MSc Business Analytics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Business Intelligence and Analytics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Forensic Accounting and Fraud Examination', 'Business, Management & Administration', 'Postgraduate'),
('MSc Public Financial Administration', 'Business, Management & Administration', 'Postgraduate'),
('MSc Health Services Management', 'Business, Management & Administration', 'Postgraduate'),
('MSc Hospitality and Tourism Management', 'Business, Management & Administration', 'Postgraduate'),
('MSc Agricultural Economics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Environmental Economics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Development Economics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Energy Economics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Transport Economics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Urban Economics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Labour Economics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Health Economics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Resource Economics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Financial Economics', 'Business, Management & Administration', 'Postgraduate'),
('MSc International Economics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Trade and Investment', 'Business, Management & Administration', 'Postgraduate'),
('MSc Export and Import Management', 'Business, Management & Administration', 'Postgraduate'),
('MSc Risk Management and Insurance', 'Business, Management & Administration', 'Postgraduate'),
('MSc Actuarial Science', 'Business, Management & Administration', 'Postgraduate'),
('MSc Statistics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Applied Statistics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Biostatistics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Financial Mathematics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Computational Mathematics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Industrial Mathematics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Mathematical Biology', 'Business, Management & Administration', 'Postgraduate'),
('MSc Mathematical Physics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Mathematical Economics', 'Business, Management & Administration', 'Postgraduate'),
('MSc Mathematical Finance', 'Business, Management & Administration', 'Postgraduate'),
('MSc Mathematical Statistics', 'Business, Management & Administration', 'Postgraduate'),
('MPhil Business Administration', 'Business, Management & Administration', 'Postgraduate'),
('MPhil Economics', 'Business, Management & Administration', 'Postgraduate'),
('MPhil Statistics', 'Business, Management & Administration', 'Postgraduate'),
('PhD Business Administration', 'Business, Management & Administration', 'Graduate'),
('PhD Economics', 'Business, Management & Administration', 'Graduate'),
('PhD Finance', 'Business, Management & Administration', 'Graduate'),
('PhD Accounting', 'Business, Management & Administration', 'Graduate'),
('PhD Marketing', 'Business, Management & Administration', 'Graduate'),
('PhD Human Resource Management', 'Business, Management & Administration', 'Graduate')
ON CONFLICT (name) DO NOTHING;

COMMIT;
