-- Migration: Insert Information Technology & Computing batch into course_programmes
-- Generated on 2024-07-21

BEGIN;

INSERT INTO public.course_programmes (name, field, level) VALUES
    ('BSc Computer Science', 'Information Technology & Computing', 'Undergraduate'),
    ('BSc Information Technology', 'Information Technology & Computing', 'Undergraduate'),
    ('BSc Software Engineering', 'Information Technology & Computing', 'Undergraduate'),
    ('BSc Data Science', 'Information Technology & Computing', 'Undergraduate'),
    ('BSc Cyber Security', 'Information Technology & Computing', 'Undergraduate'),
    ('BSc Artificial Intelligence', 'Information Technology & Computing', 'Undergraduate'),
    ('BSc Networking and Systems Administration', 'Information Technology & Computing', 'Undergraduate'),
    ('BSc Multimedia Technology', 'Information Technology & Computing', 'Undergraduate'),
    ('BSc Business Information Technology', 'Information Technology & Computing', 'Undergraduate'),
    ('BSc Management Information Systems', 'Information Technology & Computing', 'Undergraduate'),
    ('BSc Computational Biology', 'Information Technology & Computing', 'Undergraduate'),
    ('BSc Bioinformatics', 'Information Technology & Computing', 'Undergraduate'),
    ('MSc Computer Science', 'Information Technology & Computing', 'Postgraduate'),
    ('MSc Information Technology', 'Information Technology & Computing', 'Postgraduate'),
    ('MSc Data Science and Analytics', 'Information Technology & Computing', 'Postgraduate'),
    ('MSc Cyber Security', 'Information Technology & Computing', 'Postgraduate'),
    ('MSc Software Engineering', 'Information Technology & Computing', 'Postgraduate'),
    ('MPhil Computer Science', 'Information Technology & Computing', 'Postgraduate'),
    ('PhD Computer Science', 'Information Technology & Computing', 'Graduate'),
    ('MSc Digital Forensics', 'Information Technology & Computing', 'Postgraduate'),
    ('MSc Cloud Computing', 'Information Technology & Computing', 'Postgraduate'),
    ('MSc Machine Learning', 'Information Technology & Computing', 'Postgraduate'),
    ('BSc Robotics and Automation', 'Information Technology & Computing', 'Undergraduate'),
    ('BSc Internet of Things (IoT)', 'Information Technology & Computing', 'Undergraduate'),
    ('BSc Blockchain Technology', 'Information Technology & Computing', 'Undergraduate'),
    ('BSc Game Development', 'Information Technology & Computing', 'Undergraduate'),
    ('BSc Mobile Application Development', 'Information Technology & Computing', 'Undergraduate'),
    ('BSc Web Development', 'Information Technology & Computing', 'Undergraduate'),
    ('BSc Database Administration', 'Information Technology & Computing', 'Undergraduate'),
    ('BSc IT Project Management', 'Information Technology & Computing', 'Undergraduate'),
    ('BSc Digital Media Technology', 'Information Technology & Computing', 'Undergraduate'),
    ('BSc Computer Animation', 'Information Technology & Computing', 'Undergraduate'),
    ('BSc Virtual Reality and Augmented Reality', 'Information Technology & Computing', 'Undergraduate'),
    ('BSc Human-Computer Interaction', 'Information Technology & Computing', 'Undergraduate'),
    ('BSc Computational Linguistics', 'Information Technology & Computing', 'Undergraduate'),
    ('BSc Geographic Information Systems', 'Information Technology & Computing', 'Undergraduate'),
    ('BSc Remote Sensing', 'Information Technology & Computing', 'Undergraduate'),
    ('BSc Data Engineering', 'Information Technology & Computing', 'Undergraduate'),
    ('BSc DevOps Engineering', 'Information Technology & Computing', 'Undergraduate'),
    ('BSc Network Security', 'Information Technology & Computing', 'Undergraduate'),
    ('BSc Ethical Hacking', 'Information Technology & Computing', 'Undergraduate'),
    ('MSc Artificial Intelligence', 'Information Technology & Computing', 'Postgraduate'),
    ('MSc Robotics', 'Information Technology & Computing', 'Postgraduate'),
    ('MSc Internet of Things', 'Information Technology & Computing', 'Postgraduate'),
    ('MSc Blockchain and Distributed Ledger Technology', 'Information Technology & Computing', 'Postgraduate'),
    ('MSc Game Design and Development', 'Information Technology & Computing', 'Postgraduate'),
    ('MSc Mobile Computing', 'Information Technology & Computing', 'Postgraduate'),
    ('MSc Web Science', 'Information Technology & Computing', 'Postgraduate'),
    ('MSc Big Data Analytics', 'Information Technology & Computing', 'Postgraduate'),
    ('MSc Business Intelligence', 'Information Technology & Computing', 'Postgraduate'),
    ('MSc Information Systems Management', 'Information Technology & Computing', 'Postgraduate'),
    ('MSc IT Governance', 'Information Technology & Computing', 'Postgraduate'),
    ('MSc Enterprise Architecture', 'Information Technology & Computing', 'Postgraduate'),
    ('MSc IT Service Management', 'Information Technology & Computing', 'Postgraduate'),
    ('MSc Technology Management', 'Information Technology & Computing', 'Postgraduate'),
    ('MSc Innovation and Technology Management', 'Information Technology & Computing', 'Postgraduate'),
    ('MSc Digital Transformation', 'Information Technology & Computing', 'Postgraduate'),
    ('MSc E-Government', 'Information Technology & Computing', 'Postgraduate'),
    ('MSc Health Informatics', 'Information Technology & Computing', 'Postgraduate'),
    ('MSc Financial Technology (FinTech)', 'Information Technology & Computing', 'Postgraduate'),
    ('MSc Educational Technology', 'Information Technology & Computing', 'Postgraduate'),
    ('MSc Computational Neuroscience', 'Information Technology & Computing', 'Postgraduate'),
    ('MSc Quantum Computing', 'Information Technology & Computing', 'Postgraduate'),
    ('MSc Natural Language Processing', 'Information Technology & Computing', 'Postgraduate'),
    ('MSc Computer Vision', 'Information Technology & Computing', 'Postgraduate'),
    ('MSc Deep Learning', 'Information Technology & Computing', 'Postgraduate'),
    ('MSc Reinforcement Learning', 'Information Technology & Computing', 'Postgraduate'),
    ('MSc Neural Networks', 'Information Technology & Computing', 'Postgraduate'),
    ('PhD Information Technology', 'Information Technology & Computing', 'Graduate'),
    ('PhD Software Engineering', 'Information Technology & Computing', 'Graduate'),
    ('PhD Data Science', 'Information Technology & Computing', 'Graduate'),
    ('PhD Cyber Security', 'Information Technology & Computing', 'Graduate'),
    ('PhD Artificial Intelligence', 'Information Technology & Computing', 'Graduate'),
    ('PhD Robotics', 'Information Technology & Computing', 'Graduate'),
    ('PhD Machine Learning', 'Information Technology & Computing', 'Graduate'),
    ('PhD Human-Computer Interaction', 'Information Technology & Computing', 'Graduate'),
    ('PhD Computational Biology', 'Information Technology & Computing', 'Graduate'),
    ('PhD Bioinformatics', 'Information Technology & Computing', 'Graduate'),
    ('PhD Geographic Information Science', 'Information Technology & Computing', 'Graduate')
ON CONFLICT DO NOTHING;

COMMIT;
