'use server'

import Groq from 'groq-sdk'

export async function generateSlideExplanation(slideText: string, level: string, courseContext: string) {
  if (!process.env.GROQ_API_KEY) {
    throw new Error('GROQ_API_KEY is not set')
  }

  const groq = new Groq({ apiKey: process.env.GROQ_API_KEY })

  let levelPrompt = 'standard university level'
  if (level === 'ELI5') levelPrompt = 'a high school student with no prior knowledge (ELI5). Use simple analogies.'
  if (level === 'Med') levelPrompt = 'a typical undergraduate student taking this module. Focus on core concepts.'
  if (level === 'Expert') levelPrompt = 'an expert level. Dive deep into the technical nuances, advanced terminology, and underlying mechanisms.'

  const prompt = `
You are an expert university AI tutor named Alex. 
The student is studying the course: "${courseContext}".
Explain the following slide content to them at ${levelPrompt}.

Slide Content:
"${slideText}"

Format your response in clean HTML using tags like <strong>, <ul>, <li>, and <p>. Do not use markdown backticks. 
Provide a clear, engaging explanation. If there are key terms, highlight them using <strong>.
Keep it concise enough to fit in a sidebar pane (max 300 words).
`

  try {
    const chatCompletion = await groq.chat.completions.create({
      messages: [{ role: 'user', content: prompt }],
      model: 'llama-3.3-70b-versatile',
    })

    return { explanation: chatCompletion.choices[0]?.message?.content || '' }
  } catch (error: any) {
    console.error('Groq API Error Full:', error)
    
    // If the API key is rate limited or invalid, provide a beautiful mock explanation so the UI can be tested
    return {
      explanation: `
        <p><strong>Note:</strong> <em>Groq API returned an error (${error?.message?.split('.')[0] || 'Quota Exceeded'}). Showing mock response.</em></p>
        <p>This is a tailored explanation of the slide content at the <strong>${level}</strong> level.</p>
        <ul>
          <li><strong>DNA Replication</strong> is how cells make a copy of their genetic code.</li>
          <li>It uses the <strong>Semi-Conservative</strong> model, meaning half the new DNA is from the original strand.</li>
        </ul>
        <p>In a real production environment with a billed API key, this text will be dynamically generated by Groq based on your slide text.</p>
      `
    }
  }
}
